import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-workshops',
  standalone: true,
  imports: [RouterLink],
  template: `<main class="workshops-hub"><section class="hub-hero"><div class="container-xl"><p class="hub-kicker">Learn live with Java Codeex</p><h1>Upcoming workshops</h1><p>Practical live sessions where you build projects, ask questions, and learn how experienced Java developers work.</p></div></section><section class="container-xl hub-content" aria-labelledby="upcoming-title"><div class="hub-heading"><div><p class="hub-kicker">Join the next session</p><h2 id="upcoming-title">Build with guidance</h2></div><span class="hub-badge"><i class="bi bi-broadcast-pin" aria-hidden="true"></i> Live learning</span></div><article class="workshop-card"><div class="workshop-card-icon"><i class="bi bi-stars" aria-hidden="true"></i></div><div><span class="workshop-status">Registration open</span><h3>Spring Boot + AI Coding Assistant</h3><p>Build an Employee Management REST API with Spring Boot, PostgreSQL, and AI coding assistants in a focused two-hour live workshop.</p><div class="workshop-card-meta"><span><i class="bi bi-clock" aria-hidden="true"></i> 2 hours</span><span><i class="bi bi-bar-chart" aria-hidden="true"></i> Beginner friendly</span><span><i class="bi bi-ticket-perforated" aria-hidden="true"></i> Free</span></div><a class="hub-button" routerLink="/spring-boot-ai-workshop">View workshop and register <i class="bi bi-arrow-right" aria-hidden="true"></i></a></div></article><section class="experience-note"><i class="bi bi-person-workspace" aria-hidden="true"></i><div><h2>Learn from practical experience</h2><p>Every workshop is designed around real Java development practices, including APIs, databases, testing, architecture, and AI-assisted problem solving.</p></div></section></section></main>`,
  styles: [`
    .workshops-hub{min-height:60vh;color:#334155;background:#f8fafc}.hub-hero{padding:4.5rem 0;color:#fff;background:radial-gradient(circle at 80% 10%,rgba(109,179,63,.2),transparent 30%),linear-gradient(135deg,#07111f,#0c3b37)}.hub-hero h1{margin:.5rem 0 .75rem;color:#fff;font-size:clamp(2.3rem,5vw,4rem);letter-spacing:-.05em}.hub-hero p:not(.hub-kicker){max-width:42rem;margin:0;color:#c6dcd6;font-size:1.1rem}.hub-kicker{margin:0;color:#8dd968;font-size:.75rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.hub-content{padding-top:3.5rem;padding-bottom:4rem}.hub-heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:1.5rem}.hub-heading h2,.experience-note h2{margin:.4rem 0 0;color:#102a43;letter-spacing:-.04em}.hub-badge{padding:.45rem .75rem;border-radius:99px;color:#34702a;background:#e9f8df;font-size:.75rem;font-weight:800}.workshop-card{display:grid;grid-template-columns:5rem 1fr;gap:1.5rem;padding:clamp(1.4rem,4vw,2.5rem);border:1px solid #d6e6da;border-radius:1.2rem;background:#fff;box-shadow:0 1rem 2.5rem rgba(15,23,42,.07)}.workshop-card-icon{display:grid;width:4rem;height:4rem;place-items:center;border-radius:1rem;color:#173525;background:#d3f0ba;font-size:1.8rem}.workshop-status{color:#4c9c32;font-size:.75rem;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.workshop-card h3{margin:.4rem 0 .6rem;color:#102a43;font-size:clamp(1.4rem,3vw,2rem)}.workshop-card p{max-width:50rem;color:#64748b}.workshop-card-meta{display:flex;flex-wrap:wrap;gap:1rem;margin:1.1rem 0 1.4rem;color:#526b6b;font-size:.82rem;font-weight:700}.workshop-card-meta i{margin-right:.25rem;color:#4c9c32}.hub-button{display:inline-flex;align-items:center;gap:.55rem;padding:.75rem 1rem;border-radius:.65rem;color:#173012;background:linear-gradient(135deg,#b3ed73,#6db33f);font-weight:800;text-decoration:none}.hub-button:hover{color:#173012;transform:translateY(-2px)}.experience-note{display:flex;gap:1rem;align-items:flex-start;margin-top:2.5rem;padding:1.5rem;border-radius:1rem;background:#eaf7f0}.experience-note>i{color:#27883d;font-size:1.8rem}.experience-note p{max-width:50rem;margin:.5rem 0 0;color:#526b6b}.workshops-hub .container-xl{width:min(100% - 2rem,var(--app-content-width));margin-inline:auto}@media(max-width:600px){.hub-heading{align-items:flex-start;gap:1rem;flex-direction:column}.workshop-card{grid-template-columns:1fr}.workshop-card-meta{gap:.6rem .9rem}}
  `]
})
export class WorkshopsComponent {}
