import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ProjectSearchComponent } from '../../features/home/project-search.component';

@Component({
  selector: 'app-header', standalone: true, imports: [RouterLink, ProjectSearchComponent],
  template: `<header class="site-header"><div class="container-xl header-inner"><a class="brand" routerLink="/" aria-label="Java Codeex home"><span class="brand-copy"><span class="brand-name">Java Codeex</span><span class="brand-subtitle"> · Practical programming, made clear</span></span></a><app-project-search /><span class="tagline d-none d-xl-inline"><i class="bi bi-stars" aria-hidden="true"></i> Learn. Build. Grow.</span></div></header>`,
  styles: [` .site-header{position:relative;overflow:visible;color:#fff;padding:1.15rem 0;background:radial-gradient(circle at 82% 15%,rgba(34,211,238,.22),transparent 28%),linear-gradient(135deg,#081226,#172554 62%,#164e63);box-shadow:0 .35rem 1rem rgba(15,23,42,.16)}.site-header:after{position:absolute;right:0;bottom:-11rem;width:21rem;height:21rem;border:1px solid rgba(103,232,249,.18);border-radius:50%;content:"";box-shadow:0 0 0 2.5rem rgba(103,232,249,.04),0 0 0 5.5rem rgba(103,232,249,.025)}.header-inner{position:relative;z-index:1;display:flex;align-items:center;justify-content:space-between;gap:1.25rem}.header-inner app-project-search{flex:1 1 28rem;max-width:42rem;min-width:0}.brand{display:inline-flex;align-items:center;gap:1rem;color:#fff;text-decoration:none}.brand-mark-wrap{display:grid;width:4.25rem;height:4.25rem;flex:0 0 4.25rem;place-items:center;border:2px solid rgba(165,243,252,.75);border-radius:1rem;background:rgba(255,255,255,.12);box-shadow:0 .5rem 1.25rem rgba(2,8,23,.25)}.brand-mark{display:block;width:3.65rem;height:3.65rem;border-radius:.75rem;object-fit:cover}.brand-copy{display:flex;flex-direction:column;gap:.2rem}.brand-name{font-size:clamp(1.5rem,3vw,2rem);font-weight:850;letter-spacing:-.035em;line-height:1}.brand-subtitle{color:#bae6fd;font-size:.78rem;font-weight:650;letter-spacing:.035em}.tagline{color:#e0f2fe;font-size:.8rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.tagline i{margin-right:.35rem;color:#67e8f9}@media(max-width:991.98px){.header-inner{flex-wrap:wrap}.header-inner app-project-search{order:3;flex-basis:100%;max-width:none}}@media(max-width:575.98px){.site-header{padding:.85rem 0}.brand{gap:.7rem}.brand-mark-wrap{width:3.25rem;height:3.25rem;flex-basis:3.25rem;border-radius:.8rem}.brand-mark{width:2.75rem;height:2.75rem;border-radius:.6rem}.brand-subtitle{font-size:.68rem}}`]
})
export class HeaderComponent {}
