import { NavigationItem } from '../models/navigation.model';

export const MAIN_NAVIGATION: readonly NavigationItem[] = [
  {
    label: 'Java', route: '/java-tutorial-overview', icon: 'bi bi-cup-hot', children: [
      { label: 'Java Tutorial Overview', route: '/java-tutorial-overview' },
      { label: 'Introduction to Java', route: '/introduction-to-java' },
      { label: 'Download and Install Java', route: '/java-download-and-install-java' },
      { label: 'Install IntelliJ IDEA', route: '/java-download-and-install-intellij-idea' },
      { label: 'Java Methods', route: '/java-methods' },
      { label: 'Java Arrays', route: '/java-arrays' },
      { label: 'Java Strings', route: '/java-strings' },
      { label: 'Java OOP Concepts', route: '/java-oop-concepts' },
      { label: 'Java Object Class', route: '/java-object-class' },
      { label: 'Java Interfaces', route: '/java-interfaces' },
      { label: 'Java Exception Handling', route: '/java-exception-handling' },
      { label: 'Java Regular Expressions', route: '/java-regex' },
      { label: 'Java Memory Management', route: '/java-memory-allocation' },
      { label: 'Java Generics', route: '/java-generics' },
      { label: 'Java Collections Framework', route: '/java-collections' },
      { label: 'Java 8+ Features', route: '/java-8-features' },
      { label: 'Java Date and Time API', route: '/java-date-and-time-api' },
      { label: 'Java Multithreading', route: '/java-multithreading' },
      { label: 'Java File Handling', route: '/java-file-handling' },
      { label: 'Java Networking', route: '/java-networking' },
      { label: 'Java JDBC', route: '/java-jdbc' },
      { label: 'Java Marker Interfaces', route: '/java-marker-interface' }
    ]
  },
  {
    label: 'Spring Boot', route: '/spring-boot-overview', icon: 'bi bi-leaf', children: [
      { label: 'Spring Boot Overview', route: '/spring-boot-overview' },
      { label: 'Spring Boot Core Concepts', route: '/spring-boot-core' },
      { label: 'Spring Boot Setup and Installation', route: '/spring-boot/setup' },
      { label: 'Spring Boot Project Structure', route: '/project-structure' },
      { label: 'Spring Boot AOP', route: '/spring-boot-aop' },
      { label: 'Spring Boot Data JPA', route: '/spring-boot-data-jpa' },
      { label: 'Spring Boot Security', route: '/spring-boot-security' },
      { label: 'Spring Boot Global Exception Handling', route: '/spring-boot-global-exception-handling' },
      { label: 'Spring Boot Profiles', route: '/spring-boot-profiles' },
      { label: 'Spring Boot Scheduler', route: '/spring-boot-scheduler' },
      { label: 'Spring Boot REST API', route: '/spring-boot-rest-api' },
      { label: 'REST API Design Best Practices', route: '/spring-boot-rest-api-design' },
      { label: 'Spring Boot Request Validation', route: '/spring-boot-validation' },
      { label: 'Spring Boot Testing', route: '/spring-boot-testing' },
      { label: 'Spring Boot Testing Comprehensive Guide', route: '/spring-boot/testing-comprehensive' },
      { label: 'Spring Boot Actuator and Monitoring', route: '/spring-boot-actuator' },
      { label: 'Spring Boot Deployment', route: '/spring-boot-deployment' },
      { label: 'Spring Boot 2 to 3 Migration', route: '/spring-boot-2-to-3-migration' }
    ]
  },
  { label: 'Angular', route: '/angular', icon: 'bi bi-braces' },
  { label: 'Interviews', route: '/interviews', icon: 'bi bi-person-workspace' },
  { label: 'Python', route: '/python', icon: 'bi bi-code-slash' },
  {
    label: 'Hibernate', route: '/hibernate-tutorial', icon: 'bi bi-database-gear', children: [
      { label: 'Hibernate Tutorial Overview', route: '/hibernate-tutorial' },
      { label: 'Hibernate Architecture', route: '/hibernate-architecture' },
      { label: 'First Hibernate Example', route: '/hibernate-first-example' },
      { label: 'Hibernate CRUD Example', route: '/hibernate-example' },
      { label: 'Hibernate Generator Classes', route: '/hibernate-generator-classes' },
      { label: 'Hibernate Dialects', route: '/hibernate/dialects' },
      { label: 'Hibernate Collection Mapping', route: '/hibernate/collection-mapping' },
      { label: 'Hibernate List Mapping', route: '/hibernate/mapping-list' },
      { label: 'Hibernate Bag Mapping', route: '/hibernate/mapping-bag' },
      { label: 'Hibernate One-to-Many Mapping', route: '/hibernate-one-to-many-mapping-using-annotation-example' },
      { label: 'Hibernate Many-to-Many Mapping', route: '/hibernate-many-to-many-example-using-annotation' },
      { label: 'Hibernate One-to-One Mapping', route: '/hibernate-one-to-one-example-using-annotation' },
      { label: 'Hibernate Many-to-One Mapping', route: '/hibernate-many-to-one-example-using-annotation' },
      { label: 'Hibernate Bidirectional Association', route: '/hibernate/bidirectional-association' },
      { label: 'Hibernate Transaction Management', route: '/hibernate-transaction-management-example' },
      { label: 'Hibernate First-Level Cache', route: '/hibernate-first-level-cache' },
      { label: 'Hibernate Second-Level Cache', route: '/hibernate-second-level-cache' }
    ]
  },
  {
    label: 'MySQL', route: '/mysql', icon: 'bi bi-database', children: [
      { label: 'MySQL SQL', heading: true },
      { label: 'MySQL SQL', route: '/mysql/sql' }, { label: 'MySQL SELECT', route: '/mysql/select' }, { label: 'MySQL SELECT DISTINCT', route: '/mysql/select-distinct' },
      { label: 'MySQL WHERE', route: '/mysql/where' }, { label: 'MySQL ORDER BY', route: '/mysql/order-by' }, { label: 'MySQL AND', route: '/mysql/and' },
      { label: 'MySQL OR', route: '/mysql/or' }, { label: 'MySQL NOT', route: '/mysql/not' }, { label: 'MySQL INSERT INTO', route: '/mysql/insert-into' },
      { label: 'MySQL NULL Values', route: '/mysql/null-values' }, { label: 'MySQL UPDATE', route: '/mysql/update' }, { label: 'MySQL DELETE', route: '/mysql/delete' },
      { label: 'MySQL LIMIT', route: '/mysql/limit' }, { label: 'MySQL Aggregate Functions', route: '/mysql/aggregate-functions' }, { label: 'MySQL MIN()', route: '/mysql/min' },
      { label: 'MySQL MAX()', route: '/mysql/max' }, { label: 'MySQL COUNT()', route: '/mysql/count' }, { label: 'MySQL SUM()', route: '/mysql/sum' },
      { label: 'MySQL AVG()', route: '/mysql/avg' }, { label: 'MySQL LIKE', route: '/mysql/like' }, { label: 'MySQL Wildcards', route: '/mysql/wildcards' },
      { label: 'MySQL IN', route: '/mysql/in' }, { label: 'MySQL BETWEEN', route: '/mysql/between' }, { label: 'MySQL Aliases', route: '/mysql/aliases' },
      { label: 'MySQL Joins', route: '/mysql/joins' }, { label: 'MySQL INNER JOIN', route: '/mysql/inner-join' }, { label: 'MySQL LEFT JOIN', route: '/mysql/left-join' },
      { label: 'MySQL RIGHT JOIN', route: '/mysql/right-join' }, { label: 'MySQL CROSS JOIN', route: '/mysql/cross-join' }, { label: 'MySQL Self Join', route: '/mysql/self-join' },
      { label: 'MySQL UNION', route: '/mysql/union' }, { label: 'MySQL UNION ALL', route: '/mysql/union-all' }, { label: 'MySQL GROUP BY', route: '/mysql/group-by' },
      { label: 'MySQL HAVING', route: '/mysql/having' }, { label: 'MySQL EXISTS', route: '/mysql/exists' }, { label: 'MySQL ANY', route: '/mysql/any' },
      { label: 'MySQL ALL', route: '/mysql/all' }, { label: 'MySQL INSERT SELECT', route: '/mysql/insert-select' }, { label: 'MySQL CASE', route: '/mysql/case' },
      { label: 'MySQL Null Functions', route: '/mysql/null-functions' }, { label: 'MySQL Stored Procedures', route: '/mysql/stored-procedures' }, { label: 'MySQL Comments', route: '/mysql/comments' },
      { label: 'MySQL Operators', route: '/mysql/operators' },
      { label: 'MySQL Database', heading: true },
      { label: 'MySQL Create DB', route: '/mysql/create-db' }, { label: 'MySQL Drop DB', route: '/mysql/drop-db' }, { label: 'MySQL Create Table', route: '/mysql/create-table' },
      { label: 'MySQL Drop Table', route: '/mysql/drop-table' }, { label: 'MySQL Alter Table', route: '/mysql/alter-table' }, { label: 'MySQL Constraints', route: '/mysql/constraints' },
      { label: 'MySQL Not Null', route: '/mysql/not-null' }, { label: 'MySQL Unique', route: '/mysql/unique' }, { label: 'MySQL Primary Key', route: '/mysql/primary-key' },
      { label: 'MySQL Foreign Key', route: '/mysql/foreign-key' }, { label: 'MySQL Check', route: '/mysql/check' }, { label: 'MySQL Default', route: '/mysql/default' },
      { label: 'MySQL Create Index', route: '/mysql/create-index' }, { label: 'MySQL Auto Increment', route: '/mysql/auto-increment' }, { label: 'MySQL Dates', route: '/mysql/dates' },
      { label: 'MySQL Views', route: '/mysql/views' }, { label: 'MySQL Injection', route: '/mysql/injection' }, { label: 'MySQL Prepared Statements', route: '/mysql/prepared-statements' }
    ]
  },
  {
    label: 'PostgreSQL', route: '/postgresql/introduction', icon: 'bi bi-server', children: [
      { label: 'PostgreSQL Introduction', route: '/postgresql/introduction' },
      { label: 'PostgreSQL installation', route: '/postgresql/installation' },
      { label: 'PostgreSQL - pgAdmin4', route: '/postgresql/pgadmin4' },
      { label: 'PostgreSQL Create Table', route: '/postgresql/create-table' },
      { label: 'PostgreSQL Insert Data', route: '/postgresql/insert-data' },
      { label: 'PostgreSQL Select Data', route: '/postgresql/fetch-data' },
      { label: 'PostgreSQL ADD COLUMN', route: '/postgresql/add-column' },
      { label: 'PostgreSQL UPDATE', route: '/postgresql/update-data' },
      { label: 'PostgreSQL ALTER COLUMN', route: '/postgresql/alter-column' },
      { label: 'PostgreSQL DROP COLUMN', route: '/postgresql/drop-column' },
      { label: 'PostgreSQL DELETE', route: '/postgresql/delete-data' },
      { label: 'PostgreSQL DROP TABLE', route: '/postgresql/drop-table' },
      { label: 'PostgreSQL Operators', route: '/postgresql/operators' },
      { label: 'PostgreSQL SELECT', route: '/postgresql/select' },
      { label: 'PostgreSQL SELECT DISTINCT', route: '/postgresql/select-distinct' },
      { label: 'PostgreSQL WHERE', route: '/postgresql/where' },
      { label: 'PostgreSQL ORDER BY', route: '/postgresql/order-by' },
      { label: 'PostgreSQL LIMIT', route: '/postgresql/limit' },
      { label: 'PostgreSQL MIN and MAX', route: '/postgresql/min-max' },
      { label: 'PostgreSQL COUNT', route: '/postgresql/count' },
      { label: 'PostgreSQL SUM', route: '/postgresql/sum' },
      { label: 'PostgreSQL AVG', route: '/postgresql/avg' },
      { label: 'PostgreSQL LIKE', route: '/postgresql/like' },
      { label: 'PostgreSQL IN', route: '/postgresql/in' },
      { label: 'PostgreSQL BETWEEN', route: '/postgresql/between' },
      { label: 'PostgreSQL AS', route: '/postgresql/as' },
      { label: 'PostgreSQL Joins', route: '/postgresql/joins' },
      { label: 'PostgreSQL INNER JOIN', route: '/postgresql/inner-join' },
      { label: 'PostgreSQL LEFT JOIN', route: '/postgresql/left-join' },
      { label: 'PostgreSQL RIGHT JOIN', route: '/postgresql/right-join' },
      { label: 'PostgreSQL FULL JOIN', route: '/postgresql/full-join' },
      { label: 'PostgreSQL CROSS JOIN', route: '/postgresql/cross-join' },
      { label: 'PostgreSQL UNION', route: '/postgresql/union' },
      { label: 'PostgreSQL GROUP BY', route: '/postgresql/group-by' },
      { label: 'PostgreSQL HAVING', route: '/postgresql/having' },
      { label: 'PostgreSQL EXISTS', route: '/postgresql/exists' },
      { label: 'PostgreSQL ANY', route: '/postgresql/any' },
      { label: 'PostgreSQL ALL', route: '/postgresql/all' },
      { label: 'PostgreSQL CASE', route: '/postgresql/case' }
    ]
  },
  { label: 'Design Patterns', route: '/design-patterns', icon: 'bi bi-diagram-3' },
  { label: 'Spring AI', route: '/spring-ai', icon: 'bi bi-stars' }
];

export const FOOTER_NAVIGATION: readonly NavigationItem[] = [
  { label: 'Java', route: '/java-tutorial-overview' },
  { label: 'Python', route: '/python' },
  { label: 'Spring Boot', route: '/spring-boot-overview' },
  { label: 'Angular', route: '/angular' },
  { label: 'MySQL', route: '/mysql' },
  { label: 'MongoDB', route: '/mongodb' },
  { label: 'PostgreSQL', route: '/postgresql/introduction' }
];
