import { TutorialPage } from '../models/tutorial.model';

const page = (title: string, description: string, category: TutorialPage['category'], heading: string, paragraph: string, code?: string): TutorialPage => ({
  title, description, category,
  sections: [{ heading, paragraphs: [paragraph], code }]
});

export const JAVA_PAGES: Record<string, TutorialPage> = {
  'introduction-to-java': page('Introduction to Java', 'Learn Java programming from the basics of syntax, variables, control flow, classes, objects, the JVM, and practical beginner examples.', 'Java', 'What is Java?', 'Java is a strongly typed, object-oriented language designed to run consistently across platforms through the Java Virtual Machine.', 'public class HelloWorld {\n  public static void main(String[] args) {\n    System.out.println("Hello, Java");\n  }\n}'),
  methods: page('Methods in Java', 'Learn Java methods with parameters, return types, static and instance methods, overloading, varargs, access modifiers, and practical examples.', 'Java', 'Declaring a method', 'A method groups a set of statements behind a descriptive name. Keep methods small and make their inputs and outputs explicit.', 'static int add(int first, int second) {\n  return first + second;\n}'),
  arrays: page('Arrays in Java', 'Learn Java arrays, including declaration, initialization, multidimensional arrays, Arrays utilities, collections, and interview problems.', 'Java', 'Array fundamentals', 'Arrays store values of one type in contiguous indexed positions. Use enhanced for loops when you do not need the index.', 'int[] scores = { 85, 92, 78 };\nfor (int score : scores) {\n  System.out.println(score);\n}'),
  strings: page('Strings in Java', 'Learn Java strings, immutability, String methods, comparison, formatting, StringBuilder, regular expressions, and safe text processing examples.', 'Java', 'String values', 'String objects are immutable. Prefer StringBuilder when assembling text repeatedly inside a loop.', 'String greeting = "Hello".concat(", Java");'),
  collections: page('Java Collections Framework', 'Learn Java collections with practical examples of List, Set, Map, Queue, Deque, iterators, sorting, and the most useful collection implementations.', 'Java', 'Choosing a collection', 'Collections provide tested data structures and algorithms. Program to interfaces such as List and Map so implementations can change safely.', 'List<String> topics = new ArrayList<>();\ntopics.add("Collections");'),
  'date-and-time-api': page('Date and Time API in Java', 'Learn the Java Date and Time API with LocalDate, LocalTime, LocalDateTime, ZonedDateTime, Instant, formatting, parsing, and time-zone-safe examples.', 'Java', 'Use java.time', 'The java.time API separates dates, times, instants, and time zones, avoiding many ambiguities of the legacy Date API.', 'LocalDate today = LocalDate.now();\nZonedDateTime now = ZonedDateTime.now();'),
  'download-and-install-java': page('Install Java JDK', 'Install the Java JDK on Windows, macOS, or Linux, configure JAVA_HOME and PATH, choose a supported version, and verify java and javac from the command line.', 'Java', 'Verify the JDK', 'Install a supported JDK, configure JAVA_HOME when needed, and confirm both the compiler and runtime are available on PATH.', 'java --version\njavac --version'),
  'download-and-install-intellij-idea': page('Install IntelliJ IDEA for Java', 'Install IntelliJ IDEA for Java development, select a JDK, create a project, configure Maven or Gradle, and run Java code.', 'Java', 'Create a Java project', 'Select the installed JDK when creating a project, then keep project language level and build tool settings aligned with the repository.', undefined),
  'exception-handling': page('Exception Handling in Java', 'Learn Java exception handling with try-catch-finally, checked and unchecked exceptions, custom exceptions, and try-with-resources.', 'Java', 'try, catch, and finally', 'Catch the most specific exception you can handle, preserve useful context, and avoid empty catch blocks.', 'try {\n  Files.readString(path);\n} catch (IOException error) {\n  logger.error("Unable to read file", error);\n}'),
  'file-handling': page('File Handling in Java', 'Learn Java file handling with Path, Files, NIO, reading and writing text, directories, streams, resource cleanup, and safe file-operation examples.', 'Java', 'Working with Path', 'The Path API makes file operations composable and works well with try-with-resources for streams and readers.', 'Path path = Path.of("notes.txt");\nFiles.writeString(path, "Java IO");'),
  generics: page('Generics in Java', 'Learn Java generics with type parameters, generic classes and methods, bounded types, wildcards, PECS, type erasure, and collection examples.', 'Java', 'Why generics matter', 'Generics move type errors to compile time and remove many casts from application code.', 'List<String> names = new ArrayList<>();'),
  interfaces: page('Interfaces in Java', 'Learn Java interfaces with contracts, default and static methods, functional interfaces, multiple inheritance of type, and practical design examples.', 'Java', 'Program to an interface', 'Interfaces describe capabilities without forcing consumers to depend on a concrete implementation.', 'interface PaymentGateway {\n  Receipt charge(Money amount);\n}'),
  'java-8-features': page('Java 8 Features: Lambdas, Streams and Optional', 'Learn Java 8 features including lambdas, functional interfaces, streams, Optional, method references, default methods, and practical examples.', 'Java', 'Functional programming tools', 'Use streams for declarative transformations, but keep ordinary loops when they communicate the algorithm more clearly.', 'var names = users.stream()\n  .map(User::name)\n  .toList();'),
  jdbc: page('Java JDBC Database Connectivity', 'Learn Java JDBC database connectivity with drivers, PreparedStatement, ResultSet, transactions, batching, resource cleanup, SQL safety, and database examples.', 'Java', 'Parameterized SQL', 'Use prepared statements for values supplied by users or external systems, and close resources with try-with-resources.', 'try (PreparedStatement statement = connection.prepareStatement(\n    "select * from users where id = ?")) {\n  statement.setLong(1, userId);\n}'),
  'marker-interface': page('Java Marker Interfaces: Serializable and Cloneable', 'Learn Java marker interfaces with Serializable, Cloneable, Remote, Externalizable, serialization, transient fields, and safe object copying.', 'Java', 'Metadata through interfaces', 'A marker interface communicates a capability to the type system or a framework. Prefer annotations when metadata is the clearer abstraction.', undefined),
  'memory-allocation': page('Java Memory Management: JVM Memory, Class Loaders, and Garbage Collection', 'Learn Java memory management with JVM memory areas, stack versus heap, class loaders, garbage collection, memory leaks, and troubleshooting tools.', 'Java', 'Stack and heap', 'Local variables and call frames are associated with thread execution, while objects are allocated on the heap and reclaimed when unreachable.', undefined),
  multithreading: page('Multithreading in Java', 'Learn Java multithreading with threads, Runnable, executors, synchronization, locks, concurrent collections, futures, and safe shared state.', 'Java', 'Prefer executors', 'ExecutorService separates task submission from thread management and is usually easier to reason about than manually creating threads.', 'try (ExecutorService pool = Executors.newFixedThreadPool(4)) {\n  pool.submit(this::process);\n}'),
  networking: page('Networking in Java', 'Learn Java networking with sockets, TCP and UDP concepts, URL connections, the modern HTTP Client, asynchronous requests, and safe network handling.', 'Java', 'HTTP clients', 'The java.net.http client supports asynchronous requests and integrates with CompletableFuture for non-blocking workflows.', 'HttpClient client = HttpClient.newHttpClient();'),
  'oop-concepts': page('OOP Concepts in Java', 'Learn Java OOP concepts including classes, objects, encapsulation, inheritance, polymorphism, abstraction, composition, and practical design examples.', 'Java', 'Encapsulation', 'Keep an object’s invariants inside the object and expose behavior rather than mutable implementation details.', undefined),
  'object-class': page('Java Object Class Methods', 'Learn Java Object class methods including equals(), hashCode(), toString(), getClass(), clone(), wait(), notify(), and the equals–hashCode contract.', 'Java', 'The root class of Java', 'Every Java class directly or indirectly extends java.lang.Object and inherits common behavior such as toString, equals, hashCode, and getClass.', undefined),
  regex: page('Regular Expressions in Java', 'Learn Java regular expressions with Pattern, Matcher, character classes, quantifiers, groups, validation, replacement, and text processing.', 'Java', 'Compile patterns deliberately', 'Compile a Pattern once when it will be reused, and document complex expressions with named groups or tests.', 'Pattern email = Pattern.compile("^[^@]+@[^@]+$");'),
  'java-404': page('Java Page Not Found', 'The requested Java tutorial page could not be found.', 'Java', 'Page not found', 'Return to the Java course overview to continue learning.', undefined)
};

export const SPRINGBOOT_PAGES: Record<string, TutorialPage> = {
  introduction: page('Spring Boot Core Concepts', 'Learn Spring Boot fundamentals: auto-configuration, starters, dependency injection, bean lifecycle, profiles, and Java examples.', 'Spring Boot', 'Spring Boot fundamentals', 'Spring Boot combines auto-configuration, starters, embedded servers, dependency injection, and externalized configuration to reduce setup work in Java applications.', '@SpringBootApplication\npublic class Application {\n  public static void main(String[] args) {\n    SpringApplication.run(Application.class, args);\n  }\n}'),
  'project-structure': page('Spring Boot Project Structure', 'Organize controllers, services, repositories, configuration, and resources.', 'Spring Boot', 'A maintainable structure', 'Keep application boundaries visible: web adapters should call services, services should express use cases, and repositories should handle persistence.', undefined),
  aop: page('Spring Boot AOP Tutorial', 'Learn Spring Boot AOP with aspects, advice, pointcuts, join points, proxies, transactions, logging, and practical Java examples.', 'Spring Boot', 'Cross-cutting behavior', 'Use Spring Boot AOP to apply logging, security, transactions, and other cross-cutting concerns without repeating infrastructure code in every business method.', undefined),
  'data-jpa': page('Spring Boot Data JPA', 'Learn Spring Boot Data JPA with entities, repositories, CRUD operations, relationships, Hibernate queries, pagination, and practical database examples.', 'Spring Boot', 'Repositories and transactions', 'Spring Boot Data JPA reduces persistence boilerplate while service boundaries define transaction behavior, relationships, and reliable database access.', 'public interface UserRepository extends JpaRepository<User, Long> {}'),
  'hikari-connection-pool': page('Spring Boot Hikari Connection Pool', 'Learn how Spring Boot uses HikariCP for JDBC connection pooling, including pool sizing, timeouts, monitoring, and production configuration.', 'Spring Boot', 'Efficient database connections', 'HikariCP is Spring Boot’s default JDBC connection pool. It reuses database connections so applications can handle requests efficiently without opening a new connection for every query.', 'spring.datasource.hikari.maximum-pool-size=10\nspring.datasource.hikari.minimum-idle=2\nspring.datasource.hikari.connection-timeout=30000'),
  'redis-cache': page('Spring Boot Redis Cache', 'Learn how to use Redis as a distributed cache in Spring Boot with caching annotations, Redis configuration, TTL values, and cache eviction.', 'Spring Boot', 'Fast distributed caching', 'Redis stores frequently requested data in memory, while Spring Boot cache annotations let application services read from and update the cache without repeating cache-management code.', '@Cacheable(cacheNames = "students", key = "#id")\npublic Student findById(Long id) {\n  return repository.findById(id).orElseThrow();\n}'),
  'file-upload': page('Spring Boot File Upload', 'Learn how to upload, validate, store, and download files in a Spring Boot REST API with MultipartFile.', 'Spring Boot', 'Upload files with MultipartFile', 'Spring Boot handles multipart form-data through MultipartFile. Validate the file before storing it, generate a safe server-side name, and keep file storage separate from request-processing code.', '@PostMapping("/upload")\npublic ResponseEntity&lt;String&gt; upload(@RequestParam("file") MultipartFile file) {\n  return ResponseEntity.ok("Uploaded");\n}'),
  'security-comprehensive': page('Spring Boot Security', 'Learn Spring Boot 3 Security 6 with authentication, authorization, JWT, OAuth2, password hashing, roles, CSRF, CORS, method security, and testing.', 'Spring Boot', 'Authentication and authorization', 'Build secure Spring Boot applications with component-based security configuration, database users, JWT resource servers, OAuth2, and tested access rules.', undefined),
  'exception-handling': page('Spring Boot Global Exception Handling', 'Learn Spring Boot global exception handling with @RestControllerAdvice, @ExceptionHandler, validation, custom exceptions, logging, and consistent API responses.', 'Spring Boot', 'Global exception handling', 'A controller advice can translate known application exceptions into stable HTTP responses without duplicating try/catch code in every controller.', undefined),
  profiles: page('Spring Boot Profiles', 'Learn Spring Boot profiles for development, testing, staging, and production configuration with profile files, activation methods, and secure secrets.', 'Spring Boot', 'Environment-specific configuration', 'Spring Boot profiles separate environment-specific settings from application code so development, testing, staging, and production can use the right configuration safely.', undefined),
  scheduler: page('Spring Boot Scheduler', 'Learn Spring Boot scheduling with @Scheduled, cron expressions, fixed rate, fixed delay, thread pools, testing, and production safeguards.', 'Spring Boot', 'Reliable scheduled tasks', 'Spring Boot scheduling runs recurring work such as cleanup, notifications, synchronization, and reports while keeping timing, concurrency, and failure behavior explicit.', undefined),
  'rest-api': page('Spring Boot REST API', 'Learn Spring Boot REST API development with controllers, HTTP methods, CRUD operations, DTOs, validation, pagination, versioning, and practical Java examples.', 'Spring Boot', 'REST endpoint design', 'Use resource nouns, appropriate status codes, validation, and DTOs to keep the API contract stable as the domain evolves.', '@RestController\n@RequestMapping("/api/users")\nclass UserController {}'),
  'rest-api-design': page('REST API Design Best Practices', 'Learn Spring Boot REST API design with resource naming, HTTP methods, status codes, validation, pagination, versioning, and error responses.', 'Spring Boot', 'An explicit API contract', 'Spring Boot REST API design turns HTTP requests into a predictable contract: use resource nouns, choose methods and status codes deliberately, validate input, and document response shapes for clients.', undefined),
  validation: page('Spring Boot Request Validation', 'Learn Spring Boot request validation with Bean Validation, DTOs, nested objects, method parameters, business rules, and REST error responses.', 'Spring Boot', 'Validate at the boundary', 'Spring Boot request validation checks incoming DTOs before business logic runs. Use Bean Validation for field rules, service methods for business rules, and database constraints for final integrity.', '@NotBlank\nprivate String name;'),
  testing: page('Spring Boot Testing', 'Learn Spring Boot testing with JUnit, Mockito, @WebMvcTest, @DataJpaTest, @SpringBootTest, Testcontainers, and integration tests.', 'Spring Boot', 'Test the right boundary', 'Spring Boot testing combines focused unit tests, Spring test slices, and integration tests so you can verify business rules, web behavior, persistence, and application wiring.', undefined),
  'testing-comprehensive': page('Spring Boot Testing Comprehensive Guide', 'Build a layered test strategy for maintainable Spring applications.', 'Spring Boot', 'Layered testing', 'A balanced suite combines fast unit tests with a smaller number of high-value integration tests.', undefined),
  actuator: page('Spring Boot Actuator', 'Learn Spring Boot Actuator with health checks, liveness, readiness, metrics, Prometheus, Grafana, secured endpoints, custom health indicators, and production monitoring.', 'Spring Boot', 'Operational visibility', 'Spring Boot Actuator exposes operational endpoints for health, readiness, metrics, and application information. Protect the endpoints and expose only what your platform needs.', undefined),
  deployment: page('Deploy Spring Boot Applications', 'Learn Spring Boot deployment with executable JARs, Docker, Docker Compose, Kubernetes, CI/CD, external configuration, health checks, security, logging, and rollback strategies.', 'Spring Boot', 'Production checklist', 'Spring Boot deployment requires external configuration, repeatable builds, health checks, structured logs, secure secrets, and a rollback plan for failed releases.', undefined),
  'migration-2-to-3': page('Spring Boot 2 to 3 Migration', 'Learn Spring Boot 2 to 3 migration with Java 17, Jakarta EE, Security, Hibernate, tracing, testing, and deployment steps.', 'Spring Boot', 'Spring Boot 2 to 3 migration', 'A safe Spring Boot 2 to 3 migration starts with Java 17 and dependency alignment, then addresses Jakarta packages, configuration changes, security APIs, tests, and production verification.', undefined),
  'dependency-injection': page('Spring Boot Dependency Injection', 'Compose application behavior with constructor injection.', 'Spring Boot', 'Constructor injection', 'Constructor injection makes dependencies visible, supports immutable fields, and keeps classes straightforward to test.', '@Service\nclass UserService {\n  private final UserRepository repository;\n\n  UserService(UserRepository repository) {\n    this.repository = repository;\n  }\n}'),
  setup: page('Spring Boot Setup and Installation', 'Set up Java, Maven or Gradle, Spring Initializr, and your first Spring Boot project with clear steps, commands, and troubleshooting guidance.', 'Spring Boot', 'Start with Spring Initializr', 'Choose a supported Java version, select only the dependencies you need, and verify the generated project with its build tool.', undefined)
};
