import { TutorialPage } from '../models/tutorial.model';

const page = (title: string, description: string, category: TutorialPage['category'], heading: string, paragraph: string, code?: string): TutorialPage => ({
  title, description, category,
  sections: [{ heading, paragraphs: [paragraph], code }]
});

export const JAVA_PAGES: Record<string, TutorialPage> = {
  'introduction-to-java': page('Introduction to Java', 'Learn what Java is, how it works, and why it remains a popular platform.', 'Java', 'What is Java?', 'Java is a strongly typed, object-oriented language designed to run consistently across platforms through the Java Virtual Machine.', 'public class HelloWorld {\n  public static void main(String[] args) {\n    System.out.println("Hello, Java");\n  }\n}'),
  methods: page('Methods in Java', 'Define reusable behavior with clear parameters, return types, and focused responsibilities.', 'Java', 'Declaring a method', 'A method groups a set of statements behind a descriptive name. Keep methods small and make their inputs and outputs explicit.', 'static int add(int first, int second) {\n  return first + second;\n}'),
  arrays: page('Arrays in Java', 'Work with fixed-size, indexed collections of values.', 'Java', 'Array fundamentals', 'Arrays store values of one type in contiguous indexed positions. Use enhanced for loops when you do not need the index.', 'int[] scores = { 85, 92, 78 };\nfor (int score : scores) {\n  System.out.println(score);\n}'),
  strings: page('Strings in Java', 'Use the immutable String API for text processing.', 'Java', 'String values', 'String objects are immutable. Prefer StringBuilder when assembling text repeatedly inside a loop.', 'String greeting = "Hello".concat(", Java");'),
  collections: page('Collections Framework in Java', 'Choose List, Set, Map, and Queue implementations for the task at hand.', 'Java', 'Choosing a collection', 'Collections provide tested data structures and algorithms. Program to interfaces such as List and Map so implementations can change safely.', 'List<String> topics = new ArrayList<>();\ntopics.add("Collections");'),
  'date-and-time-api': page('Date and Time API in Java', 'Use java.time for safe, readable date and time operations.', 'Java', 'Use java.time', 'The java.time API separates dates, times, instants, and time zones, avoiding many ambiguities of the legacy Date API.', 'LocalDate today = LocalDate.now();\nZonedDateTime now = ZonedDateTime.now();'),
  'download-and-install-java': page('Download and Install Java', 'Set up a JDK and verify the installation on your development machine.', 'Java', 'Verify the JDK', 'Install a supported JDK, configure JAVA_HOME when needed, and confirm both the compiler and runtime are available on PATH.', 'java --version\njavac --version'),
  'download-and-install-intellij-idea': page('Download and Install IntelliJ IDEA', 'Prepare IntelliJ IDEA for productive Java development.', 'Java', 'Create a Java project', 'Select the installed JDK when creating a project, then keep project language level and build tool settings aligned with the repository.', undefined),
  'exception-handling': page('Exception Handling in Java', 'Handle recoverable failures without hiding programming errors.', 'Java', 'try, catch, and finally', 'Catch the most specific exception you can handle, preserve useful context, and avoid empty catch blocks.', 'try {\n  Files.readString(path);\n} catch (IOException error) {\n  logger.error("Unable to read file", error);\n}'),
  'file-handling': page('File Handling in Java', 'Read and write files with modern IO and NIO APIs.', 'Java', 'Working with Path', 'The Path API makes file operations composable and works well with try-with-resources for streams and readers.', 'Path path = Path.of("notes.txt");\nFiles.writeString(path, "Java IO");'),
  generics: page('Generics in Java', 'Write reusable, type-safe classes and methods.', 'Java', 'Why generics matter', 'Generics move type errors to compile time and remove many casts from application code.', 'List<String> names = new ArrayList<>();'),
  interfaces: page('Interfaces in Java', 'Define contracts and compose behavior with interfaces.', 'Java', 'Program to an interface', 'Interfaces describe capabilities without forcing consumers to depend on a concrete implementation.', 'interface PaymentGateway {\n  Receipt charge(Money amount);\n}'),
  'java-8-features': page('Java 8+ Features', 'Use lambdas, streams, Optional, and method references effectively.', 'Java', 'Functional programming tools', 'Use streams for declarative transformations, but keep ordinary loops when they communicate the algorithm more clearly.', 'var names = users.stream()\n  .map(User::name)\n  .toList();'),
  jdbc: page('Java Database Connectivity (JDBC)', 'Connect Java applications to relational databases safely.', 'Java', 'Parameterized SQL', 'Use prepared statements for values supplied by users or external systems, and close resources with try-with-resources.', 'try (PreparedStatement statement = connection.prepareStatement(\n    "select * from users where id = ?")) {\n  statement.setLong(1, userId);\n}'),
  'marker-interface': page('Marker Interfaces in Java', 'Understand Serializable, Cloneable, and the role of marker interfaces.', 'Java', 'Metadata through interfaces', 'A marker interface communicates a capability to the type system or a framework. Prefer annotations when metadata is the clearer abstraction.', undefined),
  'memory-allocation': page('Java Memory Management', 'Understand stack frames, heap objects, and garbage collection.', 'Java', 'Stack and heap', 'Local variables and call frames are associated with thread execution, while objects are allocated on the heap and reclaimed when unreachable.', undefined),
  multithreading: page('Multithreading in Java', 'Coordinate concurrent work with executors, locks, and safe state management.', 'Java', 'Prefer executors', 'ExecutorService separates task submission from thread management and is usually easier to reason about than manually creating threads.', 'try (ExecutorService pool = Executors.newFixedThreadPool(4)) {\n  pool.submit(this::process);\n}'),
  networking: page('Networking in Java', 'Build network clients with sockets and modern HTTP APIs.', 'Java', 'HTTP clients', 'The java.net.http client supports asynchronous requests and integrates with CompletableFuture for non-blocking workflows.', 'HttpClient client = HttpClient.newHttpClient();'),
  'oop-concepts': page('OOP Concepts in Java', 'Apply encapsulation, inheritance, polymorphism, and abstraction.', 'Java', 'Encapsulation', 'Keep an object’s invariants inside the object and expose behavior rather than mutable implementation details.', undefined),
  regex: page('Regular Expressions in Java', 'Match and transform text with Pattern and Matcher.', 'Java', 'Compile patterns deliberately', 'Compile a Pattern once when it will be reused, and document complex expressions with named groups or tests.', 'Pattern email = Pattern.compile("^[^@]+@[^@]+$");'),
  'java-404': page('Java Page Not Found', 'The requested Java tutorial page could not be found.', 'Java', 'Page not found', 'Return to the Java course overview to continue learning.', undefined)
};

export const SPRINGBOOT_PAGES: Record<string, TutorialPage> = {
  introduction: page('Spring Boot Core Concepts', 'Build production-ready Spring applications with sensible defaults.', 'Spring Boot', 'Spring Boot fundamentals', 'Spring Boot combines auto-configuration, starters, embedded servers, and externalized configuration to reduce setup work.', '@SpringBootApplication\npublic class Application {\n  public static void main(String[] args) {\n    SpringApplication.run(Application.class, args);\n  }\n}'),
  'project-structure': page('Spring Boot Project Structure', 'Organize controllers, services, repositories, configuration, and resources.', 'Spring Boot', 'A maintainable structure', 'Keep application boundaries visible: web adapters should call services, services should express use cases, and repositories should handle persistence.', undefined),
  aop: page('Aspect-Oriented Programming (AOP)', 'Apply cross-cutting concerns such as logging and transactions.', 'Spring Boot', 'Cross-cutting behavior', 'Use aspects for concerns that truly cross multiple components, and keep business rules in ordinary application services.', undefined),
  'data-jpa': page('Spring Data JPA', 'Persist domain models with repositories, relationships, and transactions.', 'Spring Boot', 'Repositories and transactions', 'Spring Data repositories reduce persistence boilerplate while service boundaries should define transaction behavior explicitly.', 'public interface UserRepository extends JpaRepository<User, Long> {}'),
  'security-comprehensive': page('Spring Boot Security', 'Protect applications with authentication, authorization, and secure defaults.', 'Spring Boot', 'Secure by default', 'Define access rules explicitly, store passwords using adaptive hashing, and validate authentication boundaries with integration tests.', undefined),
  'exception-handling': page('Spring Boot Exception Handling', 'Return consistent, useful responses when requests fail.', 'Spring Boot', 'Global exception handling', 'A controller advice can translate known application exceptions into stable HTTP responses without duplicating try/catch code in every controller.', undefined),
  'rest-api': page('Building REST APIs', 'Design resource-oriented HTTP endpoints with Spring Web.', 'Spring Boot', 'REST endpoint design', 'Use resource nouns, appropriate status codes, validation, and DTOs to keep the API contract stable as the domain evolves.', '@RestController\n@RequestMapping("/api/users")\nclass UserController {}'),
  'rest-api-design': page('REST API Design Best Practices', 'Create consistent, evolvable, and observable APIs.', 'Spring Boot', 'An explicit API contract', 'Document request and response shapes, use pagination for collections, and make errors predictable for client applications.', undefined),
  validation: page('Request Validation', 'Validate incoming Spring Boot requests with clear error messages.', 'Spring Boot', 'Validate at the boundary', 'Use Bean Validation annotations on request DTOs and return field-level errors that clients can act on.', '@NotBlank\nprivate String name;'),
  testing: page('Testing Spring Boot Applications', 'Test controllers, services, repositories, and application wiring.', 'Spring Boot', 'Test the right boundary', 'Use focused unit tests for business rules and Spring test slices or integration tests when framework wiring is part of the behavior.', undefined),
  'testing-comprehensive': page('Spring Boot Testing Comprehensive Guide', 'Build a layered test strategy for maintainable Spring applications.', 'Spring Boot', 'Layered testing', 'A balanced suite combines fast unit tests with a smaller number of high-value integration tests.', undefined),
  actuator: page('Spring Boot Actuator', 'Monitor health, metrics, and operational information.', 'Spring Boot', 'Operational visibility', 'Expose only the actuator endpoints that operators need, protect them, and integrate health checks with deployment infrastructure.', undefined),
  deployment: page('Deploy Spring Boot Applications', 'Prepare Spring Boot applications for reliable deployment.', 'Spring Boot', 'Production checklist', 'Externalize configuration, configure structured logs, provide health checks, and verify graceful shutdown before deployment.', undefined),
  'dependency-injection': page('Spring Boot Dependency Injection', 'Compose application behavior with constructor injection.', 'Spring Boot', 'Constructor injection', 'Constructor injection makes dependencies visible, supports immutable fields, and keeps classes straightforward to test.', '@Service\nclass UserService {\n  private final UserRepository repository;\n\n  UserService(UserRepository repository) {\n    this.repository = repository;\n  }\n}'),
  setup: page('Spring Boot Setup and Installation', 'Create and run your first Spring Boot project.', 'Spring Boot', 'Start with Spring Initializr', 'Choose a supported Java version, select only the dependencies you need, and verify the generated project with its build tool.', undefined)
};
