import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-public-workshops-calendar',
  standalone: true,
  imports: [RouterLink],
  template: `<main class="calendar-page"><section class="calendar-hero"><div class="container-xl"><p class="eyebrow">Open learning calendar</p><h1>Public Java and Developer Workshops</h1><p>Join practical live sessions, see what is coming next, and register when a public workshop opens.</p></div></section><section class="container-xl calendar-content"><div class="calendar-heading"><div><p class="eyebrow">Upcoming sessions</p><h2>Learn live with guidance</h2></div><a class="calendar-link" routerLink="/corporate-training">Need team training? View corporate programs <i class="bi bi-arrow-right" aria-hidden="true"></i></a></div><div class="event-grid">@for (event of events; track event.title) { <article class="event-card"><div class="event-date"><strong>{{ event.month }}</strong><span>{{ event.day }}</span></div><div><span class="event-status">{{ event.status }}</span><h3>{{ event.title }}</h3><p>{{ event.description }}</p><div class="event-meta"><span><i class="bi bi-clock" aria-hidden="true"></i>{{ event.duration }}</span><span><i class="bi bi-camera-video" aria-hidden="true"></i>{{ event.mode }}</span><span><i class="bi bi-ticket-perforated" aria-hidden="true"></i>{{ event.cost }}</span></div><a class="event-button" [routerLink]="event.route">View workshop <i class="bi bi-arrow-right" aria-hidden="true"></i></a></div></article> }</div><section class="calendar-note"><i class="bi bi-info-circle" aria-hidden="true"></i><div><h2>Want a private session for your team?</h2><p>Public workshops are open to individual learners. Companies can request a private Java, Spring Boot, AI, or backend engineering session.</p><a class="calendar-link" routerLink="/request-corporate-demo">Request a corporate demo</a></div></section></section></main>`,
  styles: [`.calendar-page{min-height:60vh;color:#334155;background:#f8fafc}.container-xl{width:min(100% - 2rem,var(--app-content-width));margin-inline:auto}.calendar-hero{padding:4.5rem 0;color:#fff;background:radial-gradient(circle at 80% 15%,rgba(109,179,63,.2),transparent 30%),linear-gradient(135deg,#07111f,#0c3b37)}.eyebrow{margin:0 0 .8rem;color:#8dd968;font-size:.76rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.calendar-hero h1{max-width:48rem;margin:0 0 1rem;color:#fff;font-size:clamp(2.4rem,5vw,4.5rem);letter-spacing:-.06em}.calendar-hero p:not(.eyebrow){max-width:44rem;color:#c6dcd6;font-size:1.1rem;line-height:1.7}.calendar-content{padding-top:4rem;padding-bottom:5rem}.calendar-heading{display:flex;align-items:end;justify-content:space-between;gap:1rem;margin-bottom:1.5rem}.calendar-heading h2,.calendar-note h2{margin:0;color:#102a43;font-size:clamp(1.8rem,3vw,2.7rem);letter-spacing:-.04em}.calendar-link{color:#27883d;font-weight:800;text-decoration:none}.calendar-link:hover{color:#165c28;text-decoration:underline}.event-grid{display:grid;gap:1rem}.event-card{display:grid;grid-template-columns:6rem 1fr;gap:1.5rem;padding:clamp(1.3rem,4vw,2rem);border:1px solid #d6e6da;border-radius:1.2rem;background:#fff;box-shadow:0 1rem 2.5rem rgba(15,23,42,.06)}.event-date{display:grid;width:5rem;height:5rem;place-items:center;align-content:center;border-radius:1rem;color:#173525;background:#d3f0ba;text-align:center}.event-date strong{font-size:.7rem;letter-spacing:.1em;text-transform:uppercase}.event-date span{font-size:.78rem;font-weight:800}.event-status{color:#4c9c32;font-size:.75rem;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.event-card h3{margin:.35rem 0 .5rem;color:#102a43;font-size:1.4rem}.event-card p{max-width:54rem;color:#64748b;line-height:1.65}.event-meta{display:flex;flex-wrap:wrap;gap:1rem;margin:1rem 0 1.25rem;color:#526b6b;font-size:.82rem;font-weight:700}.event-meta i{margin-right:.3rem;color:#4c9c32}.event-button{display:inline-flex;align-items:center;gap:.5rem;padding:.7rem 1rem;border-radius:.6rem;color:#173012;background:#b3ed73;font-weight:800;text-decoration:none}.calendar-note{display:flex;gap:1rem;align-items:flex-start;margin-top:2.5rem;padding:1.5rem;border-radius:1rem;background:#eaf7f0}.calendar-note>i{color:#27883d;font-size:1.5rem}.calendar-note p{color:#526b6b;line-height:1.7}.calendar-note h2{font-size:1.35rem}.calendar-note .calendar-link{display:inline-block}@media(max-width:650px){.calendar-heading{align-items:flex-start;flex-direction:column}.event-card{grid-template-columns:1fr}.event-meta{gap:.6rem .9rem}}
  `]
})
export class PublicWorkshopsCalendarComponent {
  readonly events = [
    { month: 'Next', day: 'TBA', status: 'Registration opens soon', title: 'Spring Boot + AI Coding Assistant', description: 'Build an Employee Management REST API with Spring Boot, PostgreSQL, and AI coding assistants in a focused live session.', duration: '2 hours', mode: 'Live online', cost: 'Free', route: '/spring-boot-ai-workshop' }
  ] as const;
}
