import { Routes } from '@angular/router';
import { MainLayoutComponent } from './layout/main-layout/main-layout.component';
import { SPRINGBOOT_PAGES } from './core/constants/tutorial-content';
import { CourseDocumentComponent } from './features/course-document/course-document.component';
import { JAVA_ROUTES } from './features/java/java.routes';
import { SitePagesComponent } from './features/site-pages/site-pages.component';

const javaFlatRoutes: Routes = JAVA_ROUTES
  .filter((route) => route.path && route.path !== '404' && !route.path.includes(':'))
  .map((route) => ({ ...route, path: route.path as string }));
const javaLegacyRedirects: Routes = javaFlatRoutes.map((route) => ({
  path: `java/${(route.path as string).replace(/^java-/, '')}`,
  pathMatch: 'full',
  redirectTo: route.path as string
}));

const springBootCanonicalNames: Record<string, string> = {
  introduction: 'spring-boot-core',
  'project-structure': 'project-structure',
  aop: 'spring-boot-aop',
  'data-jpa': 'spring-boot-data-jpa',
  'security-comprehensive': 'spring-boot-security',
  'exception-handling': 'spring-boot-global-exception-handling',
  profiles: 'spring-boot-profiles',
  scheduler: 'spring-boot-scheduler',
  'rest-api': 'spring-boot-rest-api',
  validation: 'spring-boot-validation',
  'rest-api-design': 'spring-boot-rest-api-design',
  testing: 'spring-boot-testing',
  actuator: 'spring-boot-actuator',
  deployment: 'spring-boot-deployment',
  'migration-2-to-3': 'spring-boot-2-to-3-migration'
};
const springBootTopicOrder = ['introduction', 'setup', 'project-structure', 'aop', 'data-jpa', 'security-comprehensive', 'exception-handling', 'profiles', 'scheduler', 'rest-api', 'rest-api-design', 'validation', 'testing', 'testing-comprehensive', 'actuator', 'deployment', 'migration-2-to-3'];
const restApiDesignSeoDates = { modifiedTime: '2026-07-26' };
const restApiDesignRouteTitle = 'REST API Design Best Practices Tutorial | Java Codeex';
const springBootValidationSeoDates = { modifiedTime: '2026-07-26' };
const springBootValidationRouteTitle = 'Spring Boot Request Validation Tutorial | Java Codeex';
const springBootTestingSeoDates = { modifiedTime: '2026-07-26' };
const springBootTestingRouteTitle = 'Spring Boot Testing Tutorial | Java Codeex';
const springBootActuatorSeoDates = { modifiedTime: '2026-07-26' };
const springBootActuatorRouteTitle = 'Spring Boot Actuator Tutorial | Java Codeex';
const springBootDeploymentSeoDates = { modifiedTime: '2026-07-26' };
const springBootDeploymentRouteTitle = 'Spring Boot Deployment Tutorial | Java Codeex';
const springBootMigrationSeoDates = { modifiedTime: '2026-07-27' };
const springBootMigrationRouteTitle = 'Spring Boot 2 to 3 Migration Guide | Java Codeex';
const springBootSecurityRouteTitle = 'Spring Boot Security Tutorial | Java Codeex';
const springBootMigrationVideo = { name: 'Spring Boot 2 to Spring Boot 3 Migration Tutorial', description: 'A practical video guide to migrating a Spring Boot 2 application to Spring Boot 3.', thumbnailUrl: 'https://i.ytimg.com/vi/0eKF-mkZYXo/maxresdefault.jpg', embedUrl: 'https://www.youtube.com/embed/0eKF-mkZYXo', contentUrl: 'https://youtu.be/0eKF-mkZYXo?si=8q1ltC9mliMGKA1I' };
const springBootExceptionHandlingVideo = { name: 'Spring Boot Global Exception Handling Tutorial', description: 'Learn how Spring Boot converts exceptions into consistent REST API error responses with RestControllerAdvice and ExceptionHandler.', thumbnailUrl: 'https://i.ytimg.com/vi/vz7blft_eik/maxresdefault.jpg', embedUrl: 'https://www.youtube.com/embed/vz7blft_eik', contentUrl: 'https://youtu.be/vz7blft_eik?si=MMMHz-lhYHuZGR8f' };
const springBootProfilesVideo = { name: 'Spring Boot Profiles Tutorial', description: 'Learn Spring Boot profiles for development, testing, staging, and production configuration.', thumbnailUrl: 'https://i.ytimg.com/vi/RT9lzRBHxQ4/maxresdefault.jpg', embedUrl: 'https://www.youtube.com/embed/RT9lzRBHxQ4', contentUrl: 'https://youtu.be/RT9lzRBHxQ4?si=KI47dgfqfaiC9RVt' };
const springBootSchedulerVideo = { name: 'Spring Boot Scheduler Tutorial', description: 'Learn Spring Boot scheduling with @EnableScheduling, @Scheduled, fixed rate, fixed delay, cron expressions, and production configuration.', thumbnailUrl: 'https://i.ytimg.com/vi/81Gd8-zaKIg/maxresdefault.jpg', embedUrl: 'https://www.youtube.com/embed/81Gd8-zaKIg', contentUrl: 'https://youtu.be/81Gd8-zaKIg?si=q55pdz-NBmZm94I0' };
const springBootSecurityVideo = { name: 'Spring Boot Security 6 Authentication and Authorization Tutorial', description: 'Learn Spring Boot Security 6 authentication, authorization, JWT, roles, password hashing, and secure API configuration.', thumbnailUrl: 'https://i.ytimg.com/vi/4ZqgBb-ck2Y/maxresdefault.jpg', embedUrl: 'https://www.youtube.com/embed/4ZqgBb-ck2Y', contentUrl: 'https://youtu.be/4ZqgBb-ck2Y?si=r51DcJcgOvQftiBE' };
const springBootCanonicalRoutes: Routes = Object.entries(springBootCanonicalNames).map(([topic, canonical]) => {
  const index = springBootTopicOrder.indexOf(topic);
  const previousTopic = springBootTopicOrder[index - 1];
  const nextTopic = springBootTopicOrder[index + 1];
  const routeForTopic = (value: string): string => `/${springBootCanonicalNames[value] ?? `spring-boot/${value}`}`;
  return {
    path: canonical,
    title: topic === 'rest-api-design' ? restApiDesignRouteTitle : topic === 'validation' ? springBootValidationRouteTitle : topic === 'testing' ? springBootTestingRouteTitle : topic === 'actuator' ? springBootActuatorRouteTitle : topic === 'deployment' ? springBootDeploymentRouteTitle : topic === 'migration-2-to-3' ? springBootMigrationRouteTitle : topic === 'security-comprehensive' ? springBootSecurityRouteTitle : `${SPRINGBOOT_PAGES[topic].title} | Java Codeex`,
    data: { fileName: `${topic}.html`, title: SPRINGBOOT_PAGES[topic].title, category: 'Spring Boot', primaryKeyword: topic === 'migration-2-to-3' ? 'Spring Boot 2 to 3 migration' : topic === 'security-comprehensive' ? 'Spring Boot Security' : topic === 'introduction' ? 'Spring Boot tutorial' : SPRINGBOOT_PAGES[topic].title, description: SPRINGBOOT_PAGES[topic].description, keywords: `${SPRINGBOOT_PAGES[topic].title}, Spring Boot Security, authentication, authorization, JWT, Spring Boot tutorial`, seo: { title: topic === 'validation' ? springBootValidationRouteTitle : topic === 'testing' ? springBootTestingRouteTitle : topic === 'actuator' ? springBootActuatorRouteTitle : topic === 'deployment' ? springBootDeploymentRouteTitle : topic === 'migration-2-to-3' ? springBootMigrationRouteTitle : topic === 'security-comprehensive' ? springBootSecurityRouteTitle : `${SPRINGBOOT_PAGES[topic].title} Tutorial | Java Codeex`, description: SPRINGBOOT_PAGES[topic].description, keyword: topic === 'migration-2-to-3' ? 'Spring Boot 2 to 3 migration' : topic === 'security-comprehensive' ? 'Spring Boot Security' : topic === 'introduction' ? 'Spring Boot tutorial' : SPRINGBOOT_PAGES[topic].title, canonicalUrl: `https://javacodeex.com/${canonical}`, keywords: `${SPRINGBOOT_PAGES[topic].title}, Spring Boot Security, authentication, authorization, JWT, Spring Boot tutorial`, ...(topic === 'rest-api-design' ? restApiDesignSeoDates : {}), ...(topic === 'validation' ? springBootValidationSeoDates : {}), ...(topic === 'testing' ? springBootTestingSeoDates : {}), ...(topic === 'actuator' ? springBootActuatorSeoDates : {}), ...(topic === 'migration-2-to-3' ? springBootMigrationSeoDates : {}), ...(topic === 'migration-2-to-3' ? { video: springBootMigrationVideo } : {}), ...(topic === 'exception-handling' ? { video: springBootExceptionHandlingVideo } : {}), ...(topic === 'profiles' ? { video: springBootProfilesVideo } : {}), ...(topic === 'scheduler' ? { video: springBootSchedulerVideo } : {}), ...(topic === 'security-comprehensive' ? { video: springBootSecurityVideo } : {}), breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'Spring Boot', url: 'https://javacodeex.com/spring-boot-overview' }, { name: SPRINGBOOT_PAGES[topic].title, url: `https://javacodeex.com/${canonical}` }] }, backRoute: '/spring-boot-overview', assetFolder: 'springboot', previousRoute: previousTopic ? routeForTopic(previousTopic) : '/spring-boot-overview', previousLabel: previousTopic ? SPRINGBOOT_PAGES[previousTopic].title : 'Spring Boot Tutorial', nextRoute: nextTopic ? routeForTopic(nextTopic) : '', nextLabel: nextTopic ? SPRINGBOOT_PAGES[nextTopic].title : '' },
    loadComponent: () => Promise.resolve(CourseDocumentComponent)
  };
});

const POSTGRESQL_QUERY_TOPICS = [
  ['operators', 'PostgreSQL Operators', 'Learn comparison, logical, arithmetic, and pattern-matching operators in PostgreSQL.'],
  ['select', 'PostgreSQL SELECT', 'Learn how to retrieve rows and columns from PostgreSQL tables with SELECT.'],
  ['select-distinct', 'PostgreSQL SELECT DISTINCT', 'Learn how to remove duplicate rows from PostgreSQL query results with SELECT DISTINCT.'],
  ['where', 'PostgreSQL WHERE', 'Learn how to filter PostgreSQL rows with WHERE conditions.'],
  ['order-by', 'PostgreSQL ORDER BY', 'Learn how to sort PostgreSQL query results with ORDER BY.'],
  ['limit', 'PostgreSQL LIMIT', 'Learn how to restrict the number of rows returned by PostgreSQL queries.'],
  ['min-max', 'PostgreSQL MIN and MAX', 'Learn how to find minimum and maximum values with PostgreSQL aggregate functions.'],
  ['count', 'PostgreSQL COUNT', 'Learn how to count PostgreSQL rows and non-null values with COUNT.'],
  ['sum', 'PostgreSQL SUM', 'Learn how to calculate totals with the PostgreSQL SUM function.'],
  ['avg', 'PostgreSQL AVG', 'Learn how to calculate averages with the PostgreSQL AVG function.'],
  ['like', 'PostgreSQL LIKE', 'Learn how to match text patterns with PostgreSQL LIKE and ILIKE.'],
  ['in', 'PostgreSQL IN', 'Learn how to match a value against a list or subquery with PostgreSQL IN.'],
  ['between', 'PostgreSQL BETWEEN', 'Learn how to filter PostgreSQL values within an inclusive range with BETWEEN.'],
  ['as', 'PostgreSQL AS', 'Learn how to use aliases for PostgreSQL columns and tables with AS.'],
  ['joins', 'PostgreSQL Joins', 'Learn how PostgreSQL joins combine related rows from multiple tables.'],
  ['inner-join', 'PostgreSQL INNER JOIN', 'Learn how to return matching rows from two PostgreSQL tables with INNER JOIN.'],
  ['left-join', 'PostgreSQL LEFT JOIN', 'Learn how to keep every left-table row with PostgreSQL LEFT JOIN.'],
  ['right-join', 'PostgreSQL RIGHT JOIN', 'Learn how to keep every right-table row with PostgreSQL RIGHT JOIN.'],
  ['full-join', 'PostgreSQL FULL JOIN', 'Learn how to keep unmatched rows from both tables with PostgreSQL FULL JOIN.'],
  ['cross-join', 'PostgreSQL CROSS JOIN', 'Learn how PostgreSQL CROSS JOIN creates a Cartesian product.'],
  ['union', 'PostgreSQL UNION', 'Learn how to combine compatible PostgreSQL query results with UNION.'],
  ['group-by', 'PostgreSQL GROUP BY', 'Learn how to group PostgreSQL rows for aggregate calculations.'],
  ['having', 'PostgreSQL HAVING', 'Learn how to filter grouped PostgreSQL results with HAVING.'],
  ['exists', 'PostgreSQL EXISTS', 'Learn how to test whether a PostgreSQL subquery returns any rows with EXISTS.'],
  ['any', 'PostgreSQL ANY', 'Learn how to compare a value with any result returned by a PostgreSQL subquery.'],
  ['all', 'PostgreSQL ALL', 'Learn how to compare a value with every result returned by a PostgreSQL subquery.'],
  ['case', 'PostgreSQL CASE', 'Learn how to return conditional values in PostgreSQL queries with CASE.']
] as const;

const postgresqlQueryRoutes: Routes = POSTGRESQL_QUERY_TOPICS.map(([slug, title, description]) => ({
  path: `postgresql/${slug}`,
  title: `${title} | Java Codeex`,
  data: {
    fileName: `${slug}.html`, assetFolder: 'postgresql', category: 'PostgreSQL', title,
    primaryKeyword: title.toLowerCase(), description,
    keywords: `${title}, PostgreSQL SQL, PostgreSQL tutorial`,
    seo: { title: `${title} | Java Codeex`, description, keyword: title.toLowerCase(), canonicalUrl: `https://javacodeex.com/postgresql/${slug}`, articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: title, url: `https://javacodeex.com/postgresql/${slug}` }] }
  },
  loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent)
}));

const MYSQL_TOPICS = [
  ['sql', 'MySQL SQL'], ['select', 'MySQL SELECT'], ['select-distinct', 'MySQL SELECT DISTINCT'], ['where', 'MySQL WHERE'], ['order-by', 'MySQL ORDER BY'], ['and', 'MySQL AND'], ['or', 'MySQL OR'], ['not', 'MySQL NOT'], ['insert-into', 'MySQL INSERT INTO'], ['null-values', 'MySQL NULL Values'], ['update', 'MySQL UPDATE'], ['delete', 'MySQL DELETE'], ['limit', 'MySQL LIMIT'], ['aggregate-functions', 'MySQL Aggregate Functions'], ['min', 'MySQL MIN()'], ['max', 'MySQL MAX()'], ['count', 'MySQL COUNT()'], ['sum', 'MySQL SUM()'], ['avg', 'MySQL AVG()'], ['like', 'MySQL LIKE'], ['wildcards', 'MySQL Wildcards'], ['in', 'MySQL IN'], ['between', 'MySQL BETWEEN'], ['aliases', 'MySQL Aliases'], ['joins', 'MySQL Joins'], ['inner-join', 'MySQL INNER JOIN'], ['left-join', 'MySQL LEFT JOIN'], ['right-join', 'MySQL RIGHT JOIN'], ['cross-join', 'MySQL CROSS JOIN'], ['self-join', 'MySQL Self Join'], ['union', 'MySQL UNION'], ['union-all', 'MySQL UNION ALL'], ['group-by', 'MySQL GROUP BY'], ['having', 'MySQL HAVING'], ['exists', 'MySQL EXISTS'], ['any', 'MySQL ANY'], ['all', 'MySQL ALL'], ['insert-select', 'MySQL INSERT SELECT'], ['case', 'MySQL CASE'], ['null-functions', 'MySQL Null Functions'], ['stored-procedures', 'MySQL Stored Procedures'], ['comments', 'MySQL Comments'], ['operators', 'MySQL Operators'], ['create-db', 'MySQL Create DB'], ['drop-db', 'MySQL Drop DB'], ['create-table', 'MySQL Create Table'], ['drop-table', 'MySQL Drop Table'], ['alter-table', 'MySQL Alter Table'], ['constraints', 'MySQL Constraints'], ['not-null', 'MySQL Not Null'], ['unique', 'MySQL Unique'], ['primary-key', 'MySQL Primary Key'], ['foreign-key', 'MySQL Foreign Key'], ['check', 'MySQL Check'], ['default', 'MySQL Default'], ['create-index', 'MySQL Create Index'], ['auto-increment', 'MySQL Auto Increment'], ['dates', 'MySQL Dates'], ['views', 'MySQL Views'], ['injection', 'MySQL Injection'], ['prepared-statements', 'MySQL Prepared Statements']
] as const;

const mysqlRoutes: Routes = MYSQL_TOPICS.map(([slug, title]) => {
  const description = `Learn ${title} with clear MySQL syntax, examples, and practical database guidance.`;
  return {
    path: `mysql/${slug}`,
    title: `${title} | Java Codeex`,
    data: { fileName: `${slug}.html`, assetFolder: 'mysql', category: 'MySQL', title, primaryKeyword: title.toLowerCase(), description, keywords: `${title}, MySQL tutorial, MySQL SQL`, seo: { title: `${title} | Java Codeex`, description, keyword: title.toLowerCase(), canonicalUrl: `https://javacodeex.com/mysql/${slug}`, articleSection: 'MySQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'MySQL', url: 'https://javacodeex.com/mysql' }, { name: title, url: `https://javacodeex.com/mysql/${slug}` }] } },
    loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent)
  };
});

export const routes: Routes = [
  {
    path: '', component: MainLayoutComponent, children: [
      { path: '', title: 'Programming Tutorials, Tech Courses & Projects | Java Codeex', data: { primaryKeyword: 'programming tutorials', description: 'Learn programming, web development, cloud, DevOps, databases, AI, system design, and popular frameworks through practical tutorials and projects.', keywords: 'programming tutorials, technology courses, web development tutorials, cloud computing, DevOps, database tutorials, artificial intelligence, system design, coding interview questions, real-world projects' }, loadComponent: () => import('./features/home/home.component').then((m) => m.HomeComponent) },
      { path: 'home', pathMatch: 'full', redirectTo: '' },
      { path: 'java-tutorila-overview', pathMatch: 'full', redirectTo: 'java-tutorial-overview' },
      { path: 'java-tutorial-overview', title: 'Java Tutorial Overview | Java Codeex', data: { fileName: 'index.html', title: 'Java Tutorial Overview', category: 'Java', primaryKeyword: 'Java tutorials', description: 'Learn Java programming from fundamentals to advanced topics with clear explanations, code examples, object-oriented programming, collections, multithreading, JDBC, and practical development guidance.', keywords: 'Java tutorials, Java programming tutorial, learn Java, core Java, Java examples, Java course', seo: { title: 'Java Tutorial Overview | Java Codeex', description: 'Learn Java programming from fundamentals to advanced topics with clear explanations, code examples, object-oriented programming, collections, multithreading, JDBC, and practical development guidance.', keyword: 'Java tutorials', canonicalUrl: 'https://javacodeex.com/java-tutorial-overview', keywords: 'Java tutorials, Java programming tutorial, learn Java, core Java, Java examples, Java course', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'Java', url: 'https://javacodeex.com/java-tutorial-overview' }] } }, loadComponent: () => import('./features/java/java-document.component').then((m) => m.JavaDocumentComponent) },
      { path: 'spring-boot-overview', title: 'Spring Boot Overview | Java Codeex', data: { fileName: 'index.html', title: 'Spring Boot Overview', category: 'Spring Boot', primaryKeyword: 'Spring Boot tutorials', description: 'Learn Spring Boot through practical tutorials covering auto-configuration, REST APIs, databases, security, testing, and deployment.', keywords: 'Spring Boot tutorials, Spring Boot tutorial, learn Spring Boot, Java backend', assetFolder: 'springboot' }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'java', pathMatch: 'full', redirectTo: 'java-tutorial-overview' },
      ...javaLegacyRedirects,
      ...javaFlatRoutes,
      { path: 'spring-boot', loadChildren: () => import('./features/springboot/springboot.routes').then((m) => m.SPRINGBOOT_ROUTES) },
      ...springBootCanonicalRoutes,
      { path: 'springboot/index.html', pathMatch: 'full', redirectTo: 'spring-boot' },
      { path: 'springboot/:topic/:section', pathMatch: 'full', redirectTo: 'spring-boot/:topic/:section' },
      { path: 'springboot/:topic', pathMatch: 'full', redirectTo: 'spring-boot/:topic' },
      { path: 'python', title: 'Python Programming Tutorials | Java Codeex', data: { category: 'Programming Course', title: 'Python Programming Tutorials', description: 'Learn Python programming fundamentals through clear explanations, practical examples, and beginner-friendly exercises.', keywords: 'Python tutorials, Python programming, learn Python, Python examples' }, loadComponent: () => import('./features/python/python.component').then((m) => m.PythonComponent) },
      { path: 'hibernate-tutorial', title: 'Hibernate Tutorial | Java Codeex', data: { category: 'Java Persistence', title: 'Hibernate Tutorial', description: 'Learn Hibernate ORM, JPA, architecture, entity mapping, caching, queries, transactions, generators, and database dialects.', keywords: 'Hibernate tutorial, Hibernate in Java, Hibernate architecture, Hibernate ORM, JPA, Hibernate dialects' }, loadComponent: () => import('./features/hibernate/hibernate-introduction.component').then((m) => m.HibernateIntroductionComponent) },
      { path: 'hibernate', pathMatch: 'full', redirectTo: 'hibernate-tutorial' },
      { path: 'hibernate-architecture', title: 'Hibernate Architecture | Java Codeex', data: { category: 'Java Persistence', title: 'Hibernate Architecture', description: 'Understand Hibernate architecture, SessionFactory, Session, transactions, persistence context, JDBC, and database layers.', keywords: 'Hibernate architecture, Hibernate SessionFactory, Hibernate Session, persistence context, Hibernate JDBC' }, loadComponent: () => import('./features/hibernate/hibernate-architecture.component').then((m) => m.HibernateArchitectureComponent) },
      { path: 'hibernate/architecture', pathMatch: 'full', redirectTo: 'hibernate-architecture' },
      { path: 'hibernate-first-example', title: 'First Hibernate Example | Java Codeex', data: { category: 'Java Persistence', title: 'First Hibernate Example', description: 'Build your first Hibernate application with an entity, configuration, database mapping, transaction, and persistent object example.', keywords: 'first Hibernate example, Hibernate application, Hibernate entity, Hibernate configuration, Hibernate SessionFactory' }, loadComponent: () => import('./features/hibernate/first-hibernate-example.component').then((m) => m.FirstHibernateExampleComponent) },
      { path: 'hibernate/first-example', pathMatch: 'full', redirectTo: 'hibernate-first-example' },
      { path: 'hibernate-example', title: 'Hibernate Example with Annotations | Java Codeex', data: { category: 'Java Persistence', title: 'Hibernate Example with Annotations', description: 'Learn how to create a Maven-based Hibernate application with JPA annotations, entity mapping, configuration, transactions, and database persistence.', keywords: 'Hibernate example, Hibernate annotations, Hibernate Maven project, JPA annotations, Hibernate Entity' }, loadComponent: () => import('./features/hibernate/hibernate-example.component').then((m) => m.HibernateExampleComponent) },
      { path: 'hibernate/example', pathMatch: 'full', redirectTo: 'hibernate-example' },
      { path: 'hibernate-generator-classes', title: 'Generator Classes in Hibernate | Java Codeex', data: { category: 'Java Persistence', title: 'Generator Classes in Hibernate', description: 'Learn Hibernate identifier generator strategies including identity, sequence, UUID, assigned, native, and legacy generator classes.', keywords: 'Hibernate generator classes, Hibernate identifier generator, Hibernate sequence, Hibernate identity, Hibernate UUID, JPA GeneratedValue' }, loadComponent: () => import('./features/hibernate/hibernate-generators.component').then((m) => m.HibernateGeneratorsComponent) },
      { path: 'hibernate/generator-classes', pathMatch: 'full', redirectTo: 'hibernate-generator-classes' },
      { path: 'hibernate/dialects', title: 'SQL Dialects in Hibernate | Java Codeex', data: { category: 'Java Persistence', title: 'SQL Dialects in Hibernate', description: 'Learn how Hibernate SQL dialects generate database-specific SQL for PostgreSQL, MySQL, Oracle, SQL Server, H2, and other databases.', keywords: 'SQL dialects in Hibernate, Hibernate dialect, Hibernate PostgreSQL dialect, Hibernate MySQL dialect, Hibernate Oracle dialect' }, loadComponent: () => import('./features/hibernate/hibernate-dialects.component').then((m) => m.HibernateDialectsComponent) },
      { path: 'hibernate/collection-mapping', title: 'Collection Mapping in Hibernate | Java Codeex', data: { category: 'Java Persistence', title: 'Collection Mapping in Hibernate', description: 'Learn Hibernate collection mapping for List, Set, Map, basic values, one-to-many relationships, many-to-many relationships, and XML mappings.', keywords: 'collection mapping in Hibernate, Hibernate List mapping, Hibernate Set mapping, Hibernate Map mapping, Hibernate one-to-many collection' }, loadComponent: () => import('./features/hibernate/hibernate-collection-mapping.component').then((m) => m.HibernateCollectionMappingComponent) },
      { path: 'hibernate/mapping-list', title: 'Mapping List in Hibernate Collection Mapping | Java Codeex', data: { category: 'Java Persistence', title: 'Mapping List in Collection Mapping', description: 'Learn how to map a Hibernate List using an XML mapping file, collection table, key column, index column, persistence, and HQL fetching.', keywords: 'Hibernate List mapping XML, mapping List in Hibernate, Hibernate collection mapping List, Hibernate list element, Hibernate key index element' }, loadComponent: () => import('./features/hibernate/hibernate-list-mapping.component').then((m) => m.HibernateListMappingComponent) },
      { path: 'hibernate/mapping-bag', title: 'Mapping Bag in Hibernate Collection Mapping | Java Codeex', data: { category: 'Java Persistence', title: 'Mapping Bag in Collection Mapping', description: 'Learn how to map a Hibernate bag using XML, collection tables, key columns, basic values, transactions, and HQL fetching.', keywords: 'Hibernate Bag mapping XML, mapping Bag in Hibernate, Hibernate collection mapping Bag, Hibernate bag element, Hibernate bag versus list' }, loadComponent: () => import('./features/hibernate/hibernate-bag-mapping.component').then((m) => m.HibernateBagMappingComponent) },
      { path: 'hibernate-one-to-many-mapping-using-annotation-example', title: 'Hibernate One-to-Many Example | Java Codeex', data: { category: 'Java Persistence', title: 'Hibernate One-to-Many Example', description: 'Learn Hibernate one-to-many mapping with Jakarta Persistence annotations, Question and Answer entities, transactions, cascading, and HQL fetch joins.', keywords: 'Hibernate one-to-many example, Hibernate OneToMany annotation, Hibernate Question Answer mapping, Hibernate cascade, Hibernate fetch join' }, loadComponent: () => import('./features/hibernate/hibernate-one-to-many.component').then((m) => m.HibernateOneToManyComponent) },
      { path: 'hibernate/one-to-many', pathMatch: 'full', redirectTo: 'hibernate-one-to-many-mapping-using-annotation-example' },
      { path: 'hibernate-many-to-many-example-using-annotation', title: 'Hibernate Many-to-Many Example | Java Codeex', data: { category: 'Java Persistence', title: 'Hibernate Many-to-Many Example', description: 'Learn Hibernate many-to-many mapping with Jakarta Persistence annotations, join tables, Question and Answer entities, cascading, and HQL fetching.', keywords: 'Hibernate many-to-many example, Hibernate ManyToMany annotation, Hibernate join table, Hibernate Question Answer mapping, Hibernate Set mapping' }, loadComponent: () => import('./features/hibernate/hibernate-many-to-many.component').then((m) => m.HibernateManyToManyComponent) },
      { path: 'hibernate/many-to-many', pathMatch: 'full', redirectTo: 'hibernate-many-to-many-example-using-annotation' },
      { path: 'hibernate-one-to-one-example-using-annotation', title: 'Hibernate One-to-One Example | Java Codeex', data: { category: 'Java Persistence', title: 'Hibernate One-to-One Example', description: 'Learn Hibernate one-to-one mapping with Jakarta Persistence annotations, shared primary keys, @MapsId, Employee and Address entities, and fetch joins.', keywords: 'Hibernate one-to-one example, Hibernate OneToOne annotation, Hibernate MapsId, Hibernate Employee Address mapping, Hibernate shared primary key' }, loadComponent: () => import('./features/hibernate/hibernate-one-to-one.component').then((m) => m.HibernateOneToOneComponent) },
      { path: 'hibernate/one-to-one', pathMatch: 'full', redirectTo: 'hibernate-one-to-one-example-using-annotation' },
      { path: 'hibernate-many-to-one-example-using-annotation', title: 'Hibernate Many-to-One Mapping | Java Codeex', data: { category: 'Java Persistence', title: 'Hibernate Many-to-One Mapping', description: 'Learn Hibernate many-to-one mapping with Jakarta Persistence annotations, Employee and Address entities, foreign keys, transactions, and HQL fetch joins.', keywords: 'Hibernate many-to-one mapping, Hibernate ManyToOne annotation, Hibernate Employee Address mapping, Hibernate foreign key, Hibernate fetch join' }, loadComponent: () => import('./features/hibernate/hibernate-many-to-one.component').then((m) => m.HibernateManyToOneComponent) },
      { path: 'hibernate/many-to-one', pathMatch: 'full', redirectTo: 'hibernate-many-to-one-example-using-annotation' },
      { path: 'hibernate/bidirectional-association', title: 'Hibernate Bidirectional Association | Java Codeex', data: { category: 'Java Persistence', title: 'Hibernate Bidirectional Association', description: 'Understand Hibernate bidirectional associations, owning and inverse sides, mappedBy, helper methods, and one-to-one, one-to-many, and many-to-many mappings.', keywords: 'Hibernate bidirectional association, Hibernate mappedBy, Hibernate owning side, bidirectional one-to-many, bidirectional many-to-many' }, loadComponent: () => import('./features/hibernate/hibernate-bidirectional.component').then((m) => m.HibernateBidirectionalComponent) },
      { path: 'hibernate-transaction-management-example', title: 'Hibernate Transaction Management | Java Codeex', data: { category: 'Java Persistence', title: 'Hibernate Transaction Management', description: 'Learn Hibernate transaction management, ACID properties, commit and rollback patterns, session cleanup, JDBC, JTA, and transaction best practices.', keywords: 'Hibernate transaction management, Hibernate transaction, Hibernate commit rollback, Hibernate ACID, Hibernate JDBC transaction, Hibernate JTA' }, loadComponent: () => import('./features/hibernate/hibernate-transactions.component').then((m) => m.HibernateTransactionsComponent) },
      { path: 'hibernate/transactions', pathMatch: 'full', redirectTo: 'hibernate-transaction-management-example' },
      { path: 'hibernate-first-level-cache', title: 'First-Level Cache in Hibernate | Java Codeex', data: { category: 'Java Persistence', title: 'First-Level Cache in Hibernate', description: 'Learn how Hibernate first-level caching works inside the Session, including persistence context, repeated lookups, clear, evict, refresh, and batch processing.', keywords: 'First Level Cache in Hibernate, Hibernate Session cache, Hibernate persistence context, Hibernate clear evict, Hibernate cache example' }, loadComponent: () => import('./features/hibernate/hibernate-first-level-cache.component').then((m) => m.HibernateFirstLevelCacheComponent) },
      { path: 'hibernate/first-level-cache', pathMatch: 'full', redirectTo: 'hibernate-first-level-cache' },
      { path: 'hibernate-second-level-cache', title: 'Second-Level Cache in Hibernate | Java Codeex', data: { category: 'Java Persistence', title: 'Second-Level Cache in Hibernate', description: 'Learn Hibernate second-level caching, SessionFactory scope, cache providers, entity cache annotations, regions, eviction, and consistency.', keywords: 'Second Level Cache Hibernate, Hibernate SessionFactory cache, Hibernate second-level cache provider, Hibernate JCache, Hibernate Ehcache, Hibernate cache regions' }, loadComponent: () => import('./features/hibernate/hibernate-second-level-cache.component').then((m) => m.HibernateSecondLevelCacheComponent) },
      { path: 'hibernate/second-level-cache', pathMatch: 'full', redirectTo: 'hibernate-second-level-cache' },
      { path: 'mysql', title: 'MySQL Tutorials | Java Codeex', data: { fileName: 'index.html', assetFolder: 'mysql', category: 'MySQL', title: 'MySQL Tutorials', primaryKeyword: 'MySQL tutorials', description: 'Learn MySQL SQL queries, database design, constraints, indexes, views, stored procedures, and secure application practices.', keywords: 'MySQL tutorials, learn MySQL, MySQL SQL, MySQL database, MySQL queries', seo: { title: 'MySQL Tutorials | Java Codeex', description: 'Learn MySQL SQL queries, database design, constraints, indexes, views, stored procedures, and secure application practices.', keyword: 'MySQL tutorials', canonicalUrl: 'https://javacodeex.com/mysql', articleSection: 'MySQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'MySQL', url: 'https://javacodeex.com/mysql' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'angular', title: 'Angular Tutorials | Java Codeex', data: { category: 'Frontend Development', title: 'Angular Tutorials', description: 'Learn Angular components, routing, services, forms, and responsive application development with practical examples.', keywords: 'Angular tutorials, learn Angular, Angular components, Angular routing' }, loadComponent: () => import('./features/course-placeholder/course-placeholder.component').then((m) => m.CoursePlaceholderComponent) },
        { path: 'interviews', title: 'Interview Questions and Preparation | Java Codeex', data: { category: 'Interview Preparation', primaryKeyword: 'interview questions', description: 'Prepare for technical, managerial, and company interview rounds with focused questions, practical guidance, and Java interview preparation tracks.', keywords: 'interview questions, technical interview questions, managerial interview questions, company interview questions, Java interview preparation' }, loadComponent: () => import('./features/interview/interview-landing.component').then((m) => m.InterviewLandingComponent) },
        { path: 'company-interview-questions', title: 'Company Interview Questions | Java Codeex', data: { category: 'Company Interview Preparation', primaryKeyword: 'company interview questions', description: 'Explore company interview experiences with interview dates, candidate experience levels, technology stacks, and practical preparation guidance.', keywords: 'company interview questions, company interview experiences, interview preparation, Java backend interview', seo: { title: 'Company Interview Questions | Java Codeex', description: 'Explore company interview experiences with interview dates, candidate experience levels, technology stacks, and practical preparation guidance.', keyword: 'company interview questions', canonicalUrl: 'https://javacodeex.com/company-interview-questions', articleSection: 'Company Interview Preparation', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'Interviews', url: 'https://javacodeex.com/interviews' }, { name: 'Company Interview Questions', url: 'https://javacodeex.com/company-interview-questions' }] } }, loadComponent: () => import('./features/interview/company-interview.component').then((m) => m.CompanyInterviewComponent) },
        { path: 'company-interview-questions/:slug', title: 'Company Interview Questions and Experience | Java Codeex', data: { category: 'Company Interview Preparation', primaryKeyword: 'company interview questions', description: 'Review company interview questions organized by Core Java, Spring Boot, production support, SQL, and other interview topics.', keywords: 'company interview questions, Java interview questions, Spring Boot interview questions, interview experience', seo: { title: 'Company Interview Questions and Experience | Java Codeex', description: 'Review company interview questions organized by Core Java, Spring Boot, production support, SQL, and other interview topics.', keyword: 'company interview questions', articleSection: 'Company Interview Preparation', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'Company Interview Questions', url: 'https://javacodeex.com/company-interview-questions' }] } }, loadComponent: () => import('./features/interview/company-interview-detail.component').then((m) => m.CompanyInterviewDetailComponent) },
      { path: 'java-technical-interview-questions', title: 'Java Technical Interview Questions | Java Codeex', data: { category: 'Java Interview Preparation', primaryKeyword: 'Java technical interview questions', description: 'Prepare for Java technical interviews with topic-based questions, practical answers, and explanations covering Core Java, OOP, collections, exceptions, multithreading, Spring Boot, Hibernate, and databases.', keywords: 'Java technical interview questions, Java interview questions, Core Java interview preparation, Java interview questions and answers' }, loadComponent: () => import('./features/interview-questions/components/interview-questions/interview-questions.component').then((m) => m.InterviewQuestionsComponent) },
      { path: 'interview-questions/java', pathMatch: 'full', redirectTo: 'java-technical-interview-questions' },
      { path: 'interview-questions', loadChildren: () => import('./features/interview-questions/interview-questions.routes').then((routes) => routes.INTERVIEW_QUESTION_ROUTES) },
      { path: 'mongodb', title: 'MongoDB Tutorials | Java Codeex', data: { category: 'Document Database', title: 'MongoDB Tutorials', description: 'Explore MongoDB documents, queries, indexes, data modeling, and application integration with practical examples.', keywords: 'MongoDB tutorials, learn MongoDB, MongoDB queries, NoSQL database' }, loadComponent: () => import('./features/course-placeholder/course-placeholder.component').then((m) => m.CoursePlaceholderComponent) },
      { path: 'postgresql', pathMatch: 'full', redirectTo: 'postgresql/introduction' },
      { path: 'postgresql/introduction', title: 'PostgreSQL Introduction | Java Codeex', data: { fileName: 'introduction.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL Introduction', primaryKeyword: 'PostgreSQL introduction', description: 'Learn what PostgreSQL is, why developers use it, and the core concepts to understand before installing and building with PostgreSQL.', keywords: 'PostgreSQL introduction, what is PostgreSQL, PostgreSQL database, PostgreSQL tutorial', seo: { title: 'PostgreSQL Introduction | Java Codeex', description: 'Learn what PostgreSQL is, why developers use it, and the core concepts to understand before installing and building with PostgreSQL.', keyword: 'PostgreSQL introduction', canonicalUrl: 'https://javacodeex.com/postgresql/introduction', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL Introduction', url: 'https://javacodeex.com/postgresql/introduction' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/pgadmin4', title: 'PostgreSQL - pgAdmin 4 | Java Codeex', data: { fileName: 'pgadmin4.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL - pgAdmin 4', primaryKeyword: 'PostgreSQL pgAdmin 4', description: 'Learn how to open pgAdmin 4, connect to PostgreSQL, create databases, browse tables, and run SQL queries.', keywords: 'PostgreSQL pgAdmin 4, pgAdmin tutorial, connect PostgreSQL pgAdmin, PostgreSQL GUI', seo: { title: 'PostgreSQL - pgAdmin 4 | Java Codeex', description: 'Learn how to open pgAdmin 4, connect to PostgreSQL, create databases, browse tables, and run SQL queries.', keyword: 'PostgreSQL pgAdmin 4', canonicalUrl: 'https://javacodeex.com/postgresql/pgadmin4', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL - pgAdmin 4', url: 'https://javacodeex.com/postgresql/pgadmin4' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/create-table', title: 'PostgreSQL Create Table | Java Codeex', data: { fileName: 'create-table.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL Create Table', primaryKeyword: 'PostgreSQL create table', description: 'Learn how to create a PostgreSQL table with SQL, choose column data types, and verify the table in pgAdmin 4.', keywords: 'PostgreSQL create table, CREATE TABLE PostgreSQL, PostgreSQL data types, pgAdmin Query Tool', seo: { title: 'PostgreSQL Create Table | Java Codeex', description: 'Learn how to create a PostgreSQL table with SQL, choose column data types, and verify the table in pgAdmin 4.', keyword: 'PostgreSQL create table', canonicalUrl: 'https://javacodeex.com/postgresql/create-table', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL Create Table', url: 'https://javacodeex.com/postgresql/create-table' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/insert-data', title: 'PostgreSQL Insert Data | Java Codeex', data: { fileName: 'insert-data.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL Insert Data', primaryKeyword: 'PostgreSQL insert data', description: 'Learn how to insert one or more rows into a PostgreSQL table and verify the saved data with SELECT queries.', keywords: 'PostgreSQL insert data, INSERT PostgreSQL, PostgreSQL insert multiple rows, pgAdmin insert data', seo: { title: 'PostgreSQL Insert Data | Java Codeex', description: 'Learn how to insert one or more rows into a PostgreSQL table and verify the saved data with SELECT queries.', keyword: 'PostgreSQL insert data', canonicalUrl: 'https://javacodeex.com/postgresql/insert-data', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL Insert Data', url: 'https://javacodeex.com/postgresql/insert-data' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/fetch-data', title: 'PostgreSQL Select Data | Java Codeex', data: { fileName: 'fetch-data.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL Select Data', primaryKeyword: 'PostgreSQL select data', description: 'Learn how to retrieve and filter PostgreSQL table data with SELECT, WHERE, ORDER BY, and LIMIT queries.', keywords: 'PostgreSQL select data, SELECT PostgreSQL, PostgreSQL WHERE, PostgreSQL ORDER BY, pgAdmin select data', seo: { title: 'PostgreSQL Select Data | Java Codeex', description: 'Learn how to retrieve and filter PostgreSQL table data with SELECT, WHERE, ORDER BY, and LIMIT queries.', keyword: 'PostgreSQL select data', canonicalUrl: 'https://javacodeex.com/postgresql/fetch-data', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL Select Data', url: 'https://javacodeex.com/postgresql/fetch-data' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/add-column', title: 'PostgreSQL ADD COLUMN | Java Codeex', data: { fileName: 'add-column.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL ADD COLUMN', primaryKeyword: 'PostgreSQL add column', description: 'Learn how to add a new column to an existing PostgreSQL table with ALTER TABLE ADD COLUMN.', keywords: 'PostgreSQL add column, ALTER TABLE ADD COLUMN, PostgreSQL table changes', seo: { title: 'PostgreSQL ADD COLUMN | Java Codeex', description: 'Learn how to add a new column to an existing PostgreSQL table with ALTER TABLE ADD COLUMN.', keyword: 'PostgreSQL add column', canonicalUrl: 'https://javacodeex.com/postgresql/add-column', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL ADD COLUMN', url: 'https://javacodeex.com/postgresql/add-column' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/update-data', title: 'PostgreSQL UPDATE | Java Codeex', data: { fileName: 'update-data.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL UPDATE', primaryKeyword: 'PostgreSQL update data', description: 'Learn how to modify existing rows in a PostgreSQL table with the UPDATE statement and WHERE clause.', keywords: 'PostgreSQL update, UPDATE PostgreSQL, PostgreSQL WHERE update', seo: { title: 'PostgreSQL UPDATE | Java Codeex', description: 'Learn how to modify existing rows in a PostgreSQL table with the UPDATE statement and WHERE clause.', keyword: 'PostgreSQL update data', canonicalUrl: 'https://javacodeex.com/postgresql/update-data', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL UPDATE', url: 'https://javacodeex.com/postgresql/update-data' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/alter-column', title: 'PostgreSQL ALTER COLUMN | Java Codeex', data: { fileName: 'alter-column.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL ALTER COLUMN', primaryKeyword: 'PostgreSQL alter column', description: 'Learn how to change a PostgreSQL column type, default value, or name with ALTER TABLE ALTER COLUMN.', keywords: 'PostgreSQL alter column, ALTER TABLE ALTER COLUMN, PostgreSQL change column type', seo: { title: 'PostgreSQL ALTER COLUMN | Java Codeex', description: 'Learn how to change a PostgreSQL column type, default value, or name with ALTER TABLE ALTER COLUMN.', keyword: 'PostgreSQL alter column', canonicalUrl: 'https://javacodeex.com/postgresql/alter-column', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL ALTER COLUMN', url: 'https://javacodeex.com/postgresql/alter-column' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/drop-column', title: 'PostgreSQL DROP COLUMN | Java Codeex', data: { fileName: 'drop-column.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL DROP COLUMN', primaryKeyword: 'PostgreSQL drop column', description: 'Learn how to remove a column from an existing PostgreSQL table with ALTER TABLE DROP COLUMN.', keywords: 'PostgreSQL drop column, ALTER TABLE DROP COLUMN, PostgreSQL remove column', seo: { title: 'PostgreSQL DROP COLUMN | Java Codeex', description: 'Learn how to remove a column from an existing PostgreSQL table with ALTER TABLE DROP COLUMN.', keyword: 'PostgreSQL drop column', canonicalUrl: 'https://javacodeex.com/postgresql/drop-column', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL DROP COLUMN', url: 'https://javacodeex.com/postgresql/drop-column' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/delete-data', title: 'PostgreSQL DELETE | Java Codeex', data: { fileName: 'delete-data.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL DELETE', primaryKeyword: 'PostgreSQL delete data', description: 'Learn how to remove selected rows or all rows from a PostgreSQL table with the DELETE statement.', keywords: 'PostgreSQL delete, DELETE PostgreSQL, PostgreSQL delete rows', seo: { title: 'PostgreSQL DELETE | Java Codeex', description: 'Learn how to remove selected rows or all rows from a PostgreSQL table with the DELETE statement.', keyword: 'PostgreSQL delete data', canonicalUrl: 'https://javacodeex.com/postgresql/delete-data', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL DELETE', url: 'https://javacodeex.com/postgresql/delete-data' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/drop-table', title: 'PostgreSQL DROP TABLE | Java Codeex', data: { fileName: 'drop-table.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL DROP TABLE', primaryKeyword: 'PostgreSQL drop table', description: 'Learn how to permanently remove a PostgreSQL table with DROP TABLE and how to avoid accidental data loss.', keywords: 'PostgreSQL drop table, DROP TABLE PostgreSQL, remove PostgreSQL table', seo: { title: 'PostgreSQL DROP TABLE | Java Codeex', description: 'Learn how to permanently remove a PostgreSQL table with DROP TABLE and how to avoid accidental data loss.', keyword: 'PostgreSQL drop table', canonicalUrl: 'https://javacodeex.com/postgresql/drop-table', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL DROP TABLE', url: 'https://javacodeex.com/postgresql/drop-table' }] } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      { path: 'postgresql/installation', title: 'PostgreSQL Installation on Windows | Java Codeex', data: { fileName: 'installation.html', assetFolder: 'postgresql', category: 'PostgreSQL', title: 'PostgreSQL installation', primaryKeyword: 'PostgreSQL installation on Windows', description: 'Install PostgreSQL on Windows with the official installer, choose the required components, configure a password, and complete the setup.', keywords: 'PostgreSQL installation, install PostgreSQL Windows, PostgreSQL installer, pgAdmin installation', seo: { title: 'PostgreSQL Installation on Windows | Java Codeex', description: 'Install PostgreSQL on Windows with the official installer, choose the required components, configure a password, and complete the setup.', keyword: 'PostgreSQL installation on Windows', canonicalUrl: 'https://javacodeex.com/postgresql/installation', imageUrl: 'https://javacodeex.com/assets/images/postgresql/01-download-page.png', imageAlt: 'PostgreSQL installation download page', modifiedTime: '2026-07-27', articleSection: 'PostgreSQL', breadcrumbs: [{ name: 'Home', url: 'https://javacodeex.com/' }, { name: 'PostgreSQL', url: 'https://javacodeex.com/postgresql' }, { name: 'PostgreSQL Installation on Windows', url: 'https://javacodeex.com/postgresql/installation' }], howTo: { name: 'How to install PostgreSQL on Windows', description: 'Follow these steps to download and install PostgreSQL on Windows using the official installer.', steps: [{ name: 'Download PostgreSQL', text: 'Open the official PostgreSQL download page, select Windows, and download the installer.' }, { name: 'Start the installer', text: 'Open the downloaded PostgreSQL installer to begin the setup wizard.' }, { name: 'Select components', text: 'Select the PostgreSQL server, pgAdmin 4, Stack Builder, and command-line tools as needed.' }, { name: 'Set the database password', text: 'Create and confirm a strong password for the PostgreSQL postgres superuser.' }, { name: 'Complete the installation', text: 'Review the settings, start the installation, and wait for PostgreSQL to finish.' }] } } }, loadComponent: () => import('./features/course-document/course-document.component').then((m) => m.CourseDocumentComponent) },
      ...postgresqlQueryRoutes,
      ...mysqlRoutes,
      { path: 'design-patterns', title: 'Design Patterns in Java | Java Codeex', data: { category: 'Design Patterns', title: 'Design Patterns in Java', primaryKeyword: 'Java design patterns', description: 'Learn Java design patterns through beginner-friendly explanations, practical examples, and real-world software design use cases.', keywords: 'Java design patterns, GoF design patterns, object-oriented design, software architecture' }, loadComponent: () => import('./features/design-patterns/design-patterns-overview.component').then((m) => m.DesignPatternsOverviewComponent) },
      { path: 'design-patterns/singleton', title: 'Singleton Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', title: 'Singleton Design Pattern in Java', primaryKeyword: 'Singleton design pattern in Java', description: 'Understand the Singleton design pattern in Java with practical implementations, thread-safety guidance, and Spring examples.', keywords: 'Singleton design pattern in Java, Java design patterns, creational patterns, thread-safe Singleton' }, loadComponent: () => import('./features/design-patterns/design-patterns.component').then((m) => m.DesignPatternsComponent) },
      { path: 'design-patterns/factory-method', title: 'Factory Method Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', title: 'Factory Method Design Pattern in Java', primaryKeyword: 'Factory Method design pattern in Java', description: 'Learn the Factory Method design pattern in Java with a simple example, clear benefits, and practical use cases.', keywords: 'Factory Method design pattern in Java, Java design patterns, creational patterns, object creation' }, loadComponent: () => import('./features/design-patterns/factory-method.component').then((m) => m.FactoryMethodComponent) },
      { path: 'design-patterns/abstract-factory', title: 'Abstract Factory Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'abstract-factory', primaryKeyword: 'Abstract Factory design pattern in Java', description: 'Learn the Abstract Factory design pattern in Java with beginner-friendly explanations, examples, and object creation use cases.', keywords: 'Abstract Factory design pattern in Java, Java design patterns, creational patterns, object families' }, loadComponent: () => import('./features/design-patterns/creational-pattern.component').then((m) => m.CreationalPatternComponent) },
      { path: 'design-patterns/builder', title: 'Builder Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'builder', primaryKeyword: 'Builder design pattern in Java', description: 'Learn the Builder design pattern in Java for creating complex objects with readable, flexible, and maintainable code.', keywords: 'Builder design pattern in Java, Java design patterns, creational patterns, object construction' }, loadComponent: () => import('./features/design-patterns/creational-pattern.component').then((m) => m.CreationalPatternComponent) },
      { path: 'design-patterns/prototype', title: 'Prototype Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'prototype', primaryKeyword: 'Prototype design pattern in Java', description: 'Learn the Prototype design pattern in Java with practical examples for cloning and reusing existing objects.', keywords: 'Prototype design pattern in Java, Java design patterns, creational patterns, object cloning' }, loadComponent: () => import('./features/design-patterns/creational-pattern.component').then((m) => m.CreationalPatternComponent) },
      { path: 'design-patterns/adapter', title: 'Adapter Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'adapter', primaryKeyword: 'Adapter design pattern in Java', description: 'Learn the Adapter design pattern in Java and connect incompatible interfaces with clear examples and practical use cases.', keywords: 'Adapter design pattern in Java, Java design patterns, structural patterns, interface compatibility' }, loadComponent: () => import('./features/design-patterns/structural-pattern.component').then((m) => m.StructuralPatternComponent) },
      { path: 'design-patterns/bridge', title: 'Bridge Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'bridge', primaryKeyword: 'Bridge design pattern in Java', description: 'Learn the Bridge design pattern in Java and separate abstraction from implementation for flexible software design.', keywords: 'Bridge design pattern in Java, Java design patterns, structural patterns, abstraction' }, loadComponent: () => import('./features/design-patterns/structural-pattern.component').then((m) => m.StructuralPatternComponent) },
      { path: 'design-patterns/composite', title: 'Composite Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'composite', primaryKeyword: 'Composite design pattern in Java', description: 'Learn the Composite design pattern in Java for treating individual objects and object groups consistently.', keywords: 'Composite design pattern in Java, Java design patterns, structural patterns, tree structures' }, loadComponent: () => import('./features/design-patterns/structural-pattern.component').then((m) => m.StructuralPatternComponent) },
      { path: 'design-patterns/decorator', title: 'Decorator Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'decorator', primaryKeyword: 'Decorator design pattern in Java', description: 'Learn the Decorator design pattern in Java to add behavior to objects dynamically without changing their classes.', keywords: 'Decorator design pattern in Java, Java design patterns, structural patterns, dynamic behavior' }, loadComponent: () => import('./features/design-patterns/structural-pattern.component').then((m) => m.StructuralPatternComponent) },
      { path: 'design-patterns/facade', title: 'Facade Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'facade', primaryKeyword: 'Facade design pattern in Java', description: 'Learn the Facade design pattern in Java and simplify access to complex subsystems with a clean interface.', keywords: 'Facade design pattern in Java, Java design patterns, structural patterns, simplified interface' }, loadComponent: () => import('./features/design-patterns/structural-pattern.component').then((m) => m.StructuralPatternComponent) },
      { path: 'design-patterns/flyweight', title: 'Flyweight Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'flyweight', primaryKeyword: 'Flyweight design pattern in Java', description: 'Learn the Flyweight design pattern in Java and reduce memory usage by sharing reusable object data.', keywords: 'Flyweight design pattern in Java, Java design patterns, structural patterns, memory optimization' }, loadComponent: () => import('./features/design-patterns/structural-pattern.component').then((m) => m.StructuralPatternComponent) },
      { path: 'design-patterns/proxy', title: 'Proxy Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'proxy', primaryKeyword: 'Proxy design pattern in Java', description: 'Learn the Proxy design pattern in Java for controlling access to objects with practical security and performance examples.', keywords: 'Proxy design pattern in Java, Java design patterns, structural patterns, access control' }, loadComponent: () => import('./features/design-patterns/structural-pattern.component').then((m) => m.StructuralPatternComponent) },
      { path: 'design-patterns/chain-of-responsibility', title: 'Chain of Responsibility Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'chain-of-responsibility', primaryKeyword: 'Chain of Responsibility design pattern in Java', description: 'Learn the Chain of Responsibility design pattern in Java with a beginner-friendly request handling example.', keywords: 'Chain of Responsibility design pattern in Java, Java design patterns, behavioral patterns, request handling' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/command', title: 'Command Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'command', primaryKeyword: 'Command design pattern in Java', description: 'Learn the Command design pattern in Java by turning requests into reusable objects for flexible execution.', keywords: 'Command design pattern in Java, Java design patterns, behavioral patterns, undo and queue operations' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/interpreter', title: 'Interpreter Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'interpreter', primaryKeyword: 'Interpreter design pattern in Java', description: 'Learn the Interpreter design pattern in Java for evaluating simple languages, rules, and expressions.', keywords: 'Interpreter design pattern in Java, Java design patterns, behavioral patterns, expression parsing' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/iterator', title: 'Iterator Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'iterator', primaryKeyword: 'Iterator design pattern in Java', description: 'Learn the Iterator design pattern in Java for traversing collections without exposing their internal structure.', keywords: 'Iterator design pattern in Java, Java design patterns, behavioral patterns, collection traversal' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/mediator', title: 'Mediator Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'mediator', primaryKeyword: 'Mediator design pattern in Java', description: 'Learn the Mediator design pattern in Java to reduce direct dependencies between communicating objects.', keywords: 'Mediator design pattern in Java, Java design patterns, behavioral patterns, loose coupling' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/memento', title: 'Memento Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'memento', primaryKeyword: 'Memento design pattern in Java', description: 'Learn the Memento design pattern in Java for saving and restoring object state without breaking encapsulation.', keywords: 'Memento design pattern in Java, Java design patterns, behavioral patterns, undo functionality' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/observer', title: 'Observer Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'observer', primaryKeyword: 'Observer design pattern in Java', description: 'Learn the Observer design pattern in Java for notifying dependent objects when a subject changes state.', keywords: 'Observer design pattern in Java, Java design patterns, behavioral patterns, event-driven systems' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/state', title: 'State Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'state', primaryKeyword: 'State design pattern in Java', description: 'Learn the State design pattern in Java by moving state-specific behavior into focused classes.', keywords: 'State design pattern in Java, Java design patterns, behavioral patterns, state-based behavior' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/strategy', title: 'Strategy Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'strategy', primaryKeyword: 'Strategy design pattern in Java', description: 'Learn the Strategy design pattern in Java and switch between interchangeable algorithms at runtime.', keywords: 'Strategy design pattern in Java, Java design patterns, behavioral patterns, interchangeable algorithms' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/template-method', title: 'Template Method Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'template-method', primaryKeyword: 'Template Method design pattern in Java', description: 'Learn the Template Method design pattern in Java by defining a reusable algorithm structure with customizable steps.', keywords: 'Template Method design pattern in Java, Java design patterns, behavioral patterns, algorithm template' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'design-patterns/visitor', title: 'Visitor Design Pattern in Java | Java Codeex', data: { category: 'Design Patterns', pattern: 'visitor', primaryKeyword: 'Visitor design pattern in Java', description: 'Learn the Visitor design pattern in Java for adding operations to object structures without changing their classes.', keywords: 'Visitor design pattern in Java, Java design patterns, behavioral patterns, object operations' }, loadComponent: () => import('./features/design-patterns/behavioral-pattern.component').then((m) => m.BehavioralPatternComponent) },
      { path: 'spring-ai', title: 'Spring AI Course | Java Codeex', data: { category: 'AI Application Development', title: 'Spring AI', description: 'Build intelligent Java applications with Spring AI, prompts, models, retrieval, and practical production patterns.' }, loadComponent: () => import('./features/course-placeholder/course-placeholder.component').then((m) => m.CoursePlaceholderComponent) },
      { path: 'about', title: 'About Java Codeex', data: { sitePage: 'about', description: 'Learn about Java Codeex, its practical programming tutorials, and its approach to developer education.' }, component: SitePagesComponent },
      { path: 'author', title: 'Author and Instructor | Java Codeex', data: { sitePage: 'author', description: 'Meet the author and instructor behind Java Codeex programming tutorials.' }, component: SitePagesComponent },
      { path: 'categories', title: 'Tutorial Categories | Java Codeex', data: { sitePage: 'categories', description: 'Explore Java Codeex tutorial categories, learning paths, and practical programming resources.' }, component: SitePagesComponent },
      { path: 'contact', title: 'Contact Java Codeex', data: { sitePage: 'contact', description: 'Contact Java Codeex with questions, corrections, suggestions, or collaboration enquiries.' }, component: SitePagesComponent },
      { path: 'privacy-policy', title: 'Privacy Policy | Java Codeex', data: { sitePage: 'privacy', description: 'Read the Java Codeex privacy policy, including information about cookies, analytics, advertising, and user choices.' }, component: SitePagesComponent },
      { path: 'terms-and-conditions', title: 'Terms and Conditions | Java Codeex', data: { sitePage: 'terms', description: 'Read the terms and conditions for using Java Codeex tutorials and website content.' }, component: SitePagesComponent },
      { path: 'disclaimer', title: 'Disclaimer | Java Codeex', data: { sitePage: 'disclaimer', description: 'Read the Java Codeex educational content, accuracy, advertising, and liability disclaimer.' }, component: SitePagesComponent },
      { path: 'designPatterns', pathMatch: 'full', redirectTo: 'design-patterns' },
      { path: 'designPatterns.html', pathMatch: 'full', redirectTo: 'design-patterns' },
      { path: 'java/index.html', pathMatch: 'full', redirectTo: 'java' },
      { path: '**', data: { robots: 'noindex, nofollow' }, loadComponent: () => import('./shared/components/not-found/not-found.component').then((m) => m.NotFoundComponent) }
    ]
  }
];
