import { Component } from '@angular/core';
import { FOOTER_NAVIGATION } from '../../core/constants/navigation.config';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [],
  template: `<footer class="site-footer"><div class="container-xl"><div class="site-footer-grid"><div class="site-footer-about"><a class="site-footer-brand" href="/">Java Codeex</a><p>Learn programming, frameworks, and databases through clear explanations, practical examples, and real-world projects.</p></div><div><h2>Courses</h2><nav class="site-footer-links" aria-label="Course links">@for (item of links; track item.label) { <a [href]="item.route">{{ item.label }}</a>&#32; }</nav></div><div><h2>Company</h2><nav class="site-footer-links" aria-label="Company links"><a href="/about">About Us</a>&#32;<a href="/author">Author</a>&#32;<a href="/categories">Categories</a>&#32;<a href="/contact">Contact Us</a></nav></div><div><h2>Legal</h2><nav class="site-footer-links" aria-label="Legal links"><a href="/privacy-policy">Privacy Policy</a>&#32;<a href="/terms-and-conditions">Terms and Conditions</a>&#32;<a href="/disclaimer">Disclaimer</a></nav></div></div><div class="site-footer-contact"><p>Questions or suggestions?</p><a href="mailto:contact&#64;javacodeex.com">contact&#64;javacodeex.com</a>&#32;<a href="https://wa.me/919390416489?text=Hello%20Java%20Codeex%2C%20I%20have%20an%20enquiry." target="_blank" rel="noopener noreferrer">WhatsApp: +91 93904 16489</a>&#32;<a href="https://javacodeex.com" target="_blank" rel="noopener">javacodeex.com</a></div><div class="site-footer-bottom"><span>&copy; {{ year }} Java Codeex</span><span>Learn. Build. Grow.</span></div></div></footer>`,
  styles: [`.site-footer{margin-top:4rem;padding:3rem 0 1rem;background:#101a35;color:#cdd6f4}.site-footer-grid{display:grid;grid-template-columns:1.35fr 1fr 1fr 1fr;gap:2rem}.site-footer-brand{display:inline-block;margin-bottom:.8rem;color:#fff;font-size:1.35rem;font-weight:800;text-decoration:none}.site-footer-brand:hover{color:#f8a100}.site-footer p{max-width:390px;margin-bottom:0;color:#a6adc8;line-height:1.7}.site-footer h2{margin:0 0 .9rem;color:#f8a100;font-size:.9rem;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.site-footer-links{display:grid;gap:.55rem}.site-footer a{color:#dbeafe;text-decoration:none}.site-footer a:hover{color:#fbbf24;text-decoration:underline}.site-footer-contact{display:flex;align-items:center;gap:1rem;margin-top:2rem;padding-top:1rem;border-top:1px solid rgba(203,213,225,.18)}.site-footer-contact p{margin:0}.site-footer-contact a{color:#dbeafe}.site-footer-bottom{display:flex;justify-content:space-between;gap:1rem;margin-top:1rem;padding-top:1rem;border-top:1px solid rgba(203,213,225,.18);color:#8f9bb8;font-size:.82rem}@media(max-width:991.98px){.site-footer-grid{grid-template-columns:1fr 1fr}.site-footer-about{grid-column:span 2}}@media(max-width:767.98px){.site-footer-grid{grid-template-columns:1fr;gap:1.8rem}.site-footer-about{grid-column:auto}.site-footer-contact{align-items:flex-start;flex-direction:column;gap:.35rem}.site-footer-bottom{align-items:flex-start;flex-direction:column}}`]
})
export class FooterComponent {
  readonly links = FOOTER_NAVIGATION;
  readonly year = new Date().getFullYear();
}
