export const siteUrl = 'https://javacodeex.in';

const java = ['introduction-to-java', 'download-and-install-java', 'download-and-install-intellij-idea', 'methods', 'arrays', 'strings', 'oop-concepts', 'object-class', 'interfaces', 'exception-handling', 'regex', 'memory-allocation', 'generics', 'collections', 'java-8-features', 'date-and-time-api', 'multithreading', 'file-handling', 'networking', 'jdbc', 'marker-interface'];
const springBoot = ['introduction', 'setup', 'project-structure', 'aop', 'data-jpa', 'security-comprehensive', 'exception-handling', 'rest-api', 'rest-api-design', 'validation', 'testing', 'testing-comprehensive', 'actuator', 'deployment'];
const patterns = ['singleton', 'factory-method', 'abstract-factory', 'builder', 'prototype', 'adapter', 'bridge', 'composite', 'decorator', 'facade', 'flyweight', 'proxy', 'chain-of-responsibility', 'command', 'interpreter', 'iterator', 'mediator', 'memento', 'observer', 'state', 'strategy', 'template-method', 'visitor'];

const legacyPublicRoutes = [
  '/', '/java-tutorila-overview', '/java', ...java.map((topic) => `/java/${topic}`), '/spring-boot', '/spring-boot-core', '/spring-boot/setup', '/spring-boot/project-structure', '/spring-boot-aop', '/spring-boot-data-jpa', '/spring-boot-security', '/spring-boot-global-exception-handling', '/spring-boot-rest-api', '/spring-boot-rest-api-design', '/spring-boot-validation', '/spring-boot/testing', '/spring-boot/testing-comprehensive', '/spring-boot-actuator', '/spring-boot-deployment', '/hibernate-tutorial', '/hibernate-architecture', '/hibernate-first-example', '/hibernate-example', '/hibernate-generator-classes', '/hibernate/dialects', '/hibernate/collection-mapping', '/hibernate/mapping-list', '/hibernate/mapping-bag', '/hibernate-one-to-many-mapping-using-annotation-example', '/hibernate-many-to-many-example-using-annotation', '/hibernate-one-to-one-example-using-annotation', '/hibernate-many-to-one-example-using-annotation', '/hibernate/bidirectional-association', '/hibernate-transaction-management-example', '/hibernate-first-level-cache', '/hibernate-second-level-cache',
  '/python', '/angular', '/hibernate-tutorial', '/mysql', '/mongodb', '/postgresql', '/spring-ai', '/design-patterns', '/interviews',
  '/java-technical-interview-questions', '/interview-questions/java-oops', '/interview-questions/java-exception-handling', '/interview-questions/java-collections', '/interview-questions/java-garbage-collection', '/interview-questions/java-multithreading', '/interview-questions/java-strings', '/interview-questions/java-design-patterns',
  '/interview-questions/spring-boot', '/interview-questions/spring-boot-fundamentals', '/interview-questions/spring-boot-auto-configuration', '/interview-questions/spring-boot-annotations', '/interview-questions/spring-boot-dependency-injection', '/interview-questions/spring-boot-rest-api', '/interview-questions/spring-boot-configuration', '/interview-questions/spring-boot-data-jpa', '/interview-questions/spring-boot-transactions', '/interview-questions/spring-boot-security', '/interview-questions/spring-boot-actuator', '/interview-questions/spring-boot-logging', '/interview-questions/spring-boot-caching', '/interview-questions/spring-boot-production-performance', '/interview-questions/spring-boot-3',
  '/interview-questions/hibernate', '/interview-questions/kafka', '/interview-questions/microservices', '/interview-questions/database', ...patterns.map((pattern) => `/design-patterns/${pattern}`)
];

export const publicRoutes = [...new Set(legacyPublicRoutes
  .map((route) => route === '/java-tutorila-overview' ? '/java-tutorial-overview' : route.startsWith('/java/') ? (route.slice('/java/'.length) === 'introduction-to-java' ? '/introduction-to-java' : `/${route.slice('/java/'.length).startsWith('java-') ? route.slice('/java/'.length) : `java-${route.slice('/java/'.length)}`}`) : route.startsWith('/') && java.includes(route.slice(1)) ? `/${route.slice(1) === 'introduction-to-java' || route.slice(1).startsWith('java-') ? route.slice(1) : `java-${route.slice(1)}`}` : route)
  .filter((route) => route !== '/java'))];
